# load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:

  # make sure users exist on the system
  - import_tasks: users/rafael.yml

  # set up ansible environment
  - import_tasks: ansible_setup.yml
