#+TITLE: Config file for i3/Sway window manager
#+AUTHOR: Rafael Ito
#+PROPERTY: header-args
#+DESCRIPTION: config file for i3/Sway window manager
#+STARTUP: showeverything
#+auto_tangle: t

* Table of contents :toc_1:
- [[#general-config][General config]]
- [[#sway][Sway]]
- [[#outputs][Outputs]]
- [[#workspaces-definition][Workspaces definition]]
- [[#i3bang-raw-section-beginning][i3bang: raw section (beginning)]]
- [[#media-control][Media control]]
- [[#opacity][Opacity]]
- [[#window-settings][Window settings]]
- [[#restart-i3sway][Restart i3/sway]]
- [[#workspaces-navigation][Workspaces navigation]]
- [[#custom-keybindings][Custom keybindings]]
- [[#logitech-mx][Logitech MX]]
- [[#mouse-keybindings][Mouse keybindings]]
- [[#rotate-screen][Rotate screen]]
- [[#i3bang-raw-section-end][i3bang: raw section (end)]]
- [[#modes][Modes]]
- [[#applications-default-ws][Applications default WS]]
- [[#scratchpads][Scratchpads]]
- [[#vpn][VPN]]
- [[#startup-commands][Startup commands]]
* General config
** Modifiers
| modifier | keys                           |
|----------+--------------------------------|
| Shift    | Shift_L, Shift_R, Henkan       |
| Control  | Control_L, Control_R, Muhenkan |
| Lock     | Caps_Lock                      |
| Mod1     | Alt_L, Alt_R                   |
| Mod2     | Num_Lock                       |
| Mod3     | Super_R                        |
| Mod4     | Super_L                        |
#+begin_src conf :noweb-ref general
set $alt Mod1
set $mod Mod4
set $super_R Mod3
#+end_src
** Variables
#+begin_src conf :noweb-ref general
set $XDG_CONFIG_HOME $HOME/.config
set $SCRIPT_PATH $XDG_CONFIG_HOME/scripts
#+end_src
** General
Set window border.
#+begin_src conf :noweb-ref general
#for_window [class=".*"] border pixel 3
default_border pixel 5
#+end_src

Use Mouse+$mod to drag floating windows.
#+begin_src conf :noweb-ref general
floating_modifier $mod
#+end_src

Enable previous workspace switching.
#+begin_src conf :noweb-ref general
workspace_auto_back_and_forth yes
#+end_src

Gaps size
#+begin_src conf :noweb-ref general
gaps inner 10
#+end_src
** Font & color
Set font for window titles.
#+begin_src conf :noweb-ref general
font pango:monospace 10
#+end_src

Set ws background, text and htext colors.
#+begin_src conf :noweb-ref general
set $bg-color    #2f343f
set $text-color  #f3f4f5
set $htext_color #9575cd
#+end_src

Change colors.
#+begin_src conf :noweb-ref general
# class                 border  backgr. text    indicator child_border
#client.focused          #4c7899 #285577 #ffffff #2e9ef4   #285577
client.focused          #8cB8D9 #285577 #ffffff #2e9ef4   #285577
client.focused_inactive #333333 #5f676a #ffffff #484e50   #5f676a
client.unfocused        #333333 #222222 #888888 #292d2e   #222222
client.urgent           #2f343a #900000 #ffffff #900000   #900000
client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c
client.background       #ffffff
#+end_src
** Tangle :noexport:
*** i3
#+begin_src conf :noweb yes :tangle _config_i3
<<general>>
#+end_src
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<general>>
#+end_src
* Sway
** xdg-desktop-portal-wlr
#+begin_src conf :noweb-ref sway-input
include /etc/sway/config.d/*
#+end_src
** Mouse warping
#+begin_src conf :noweb-ref sway-mouse-warping
exec echo 1 > /tmp/mouse_warping.tmp
mouse_warping container
#+end_src
** Inputs
*** Trackpad
documentation:
https://wayland.freedesktop.org/libinput/doc/latest/index.html
#+begin_src conf :noweb-ref sway-input
input type:touchpad {
    tap enabled                                   # tap-to-click
    natural_scroll enabled                        # natural scrolling
}
#+end_src
*** Enable NumLock
#+begin_src conf :noweb-ref sway-input
input type:keyboard xkb_numlock enabled
#+end_src
*** Keyboard
**** Model, layout and variant
Load model, layout and variant for all keyboards.
#+begin_src conf :noweb-ref sway-input
input type:keyboard {
    xkb_model "pc105"
    xkb_layout "us"
    xkb_variant "intl"
}
#+end_src
**** Options
Load generic modifications for all inputs.
#+begin_src conf :noweb-ref sway-input
input * {
    xkb_options "\
        modifiers:modifiers, \
        fn-keys:fnkeys, \
    "
}
#+end_src
** Tangle :noexport:
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<sway-input>>
<<sway-mouse-warping>>
#+end_src
* Outputs
** Default Scenario
This setup is used for the main workstation.
*** Set order
#+begin_src comment :tangle no
# Outputs:
#
#   +-----------+ +-----------+ +--------+
#   |           | |           | |        |=++
#   | secondary | |  primary  | | terti..| ||
#   |           | |           | |  ..ary | ||
#   +-----------+ +-----------+ |        | ||
#   +---/   \--+  +--/   \---+  |        | ||
#   |----------|  |----------|  +--------+ ||
# --+----------+--+----------+-------------++--
#
#+end_src
**** i3
For X11, it's possible to get the output names directly from xrandr.
#+begin_src conf :tangle no
set $laptop    eDP-1
set $primary   $(xrandr | grep ' connected' | awk '{print $1}' | head -n1 | tail -n1)
set $secondary $(xrandr | grep ' connected' | awk '{print $1}' | head -n2 | tail -n1)
set $tertiary  $(xrandr | grep ' connected' | awk '{print $1}' | head -n3 | tail -n1)
#+end_src

However, setting the outputs "hardcoded" seems to be more consistent.
#+begin_src conf :noweb-ref i3-output-default
set $laptop    eDP-1
set $primary   HDMI1
set $secondary VGA1
set $tertiary  HDMI2
#+end_src
**** Sway
#+begin_src conf :noweb-ref sway-output-default
set $laptop    eDP-1
set $primary   HDMI1
set $secondary HDMI3
set $tertiary  VGA1
#+end_src
*** Set resolution
**** i3
Outputs in i3wm is now being configured through a script (=xrandr-config.sh=), called in the [[*Startup commands]].
#+begin_src conf :noweb-ref i3-output-xrandr
exec xrandr --output $primary   --mode 1920x1080 --rate 60.00 --brightness 1 --pos 0x0 --primary
exec xrandr --output $secondary --mode 1920x1080 --rate 60.00 --brightness 1 --pos -1920x0
exec xrandr --output $tertiary  --mode 1920x1080 --rate 60.00 --brightness 1 --pos 1920x0 --rotate right
#+end_src
**** Sway
#+begin_src conf :noweb-ref sway-output-default
output $primary   mode 1920x1080@60hz position     0,0 scale 1
output $secondary mode 1920x1080@60hz position -1920,0 scale 1
output $tertiary  mode 1920x1080@60hz position  1920,0 scale 1 transform 90
#+end_src
** MSc presentation
*** Set order
#+begin_src comment :tangle no
# Room:
#
#   +----------------------+
#   |                      |
#   |    +-----+ +-----+   |
#   |    | tv1 | | tv2 |   |
#   |    +-----+ +-----+   |
#   |                      |
#   |     +--+     +--+    |
#   |   x |  |  3  |  | x  |
#   |   x |  |     |  | x  |
#   |   x |  |     |  | x  |
#   |   x |  |     |  | x  |
#   |      \  \___/  /     |
#   |    x  \___ 1 _/  x   |
#   |           x          |
#   |                      |
#   |       === 2 ===      |
#   +----------------------+
#
#   x: seats
#
#   1: laptop     native screen
#   2: projector  native HDMI --> EPSON projector
#   3: educart    USB-C HDMI --> Dell monitor
#
#+end_src
#+begin_src conf :noweb-ref sway-output-msc
set $laptop    eDP-1
set $projector HDMI-A-1
set $educart   DP-1
#+end_src
*** Set resolution
#+begin_src conf :noweb-ref sway-output-msc
output $laptop    mode 1920x1080@60hz position 0,0
output $projector mode 1920x1200@60hz position 0,1080 scale 1
output $educart   mode 1920x1080@60hz position 0,-1080 scale 1
#+end_src
** Hub Viva-Bem 1
*** Set order
#+begin_src comment :tangle no
# Outputs:
#
#   +-------+ +-------+
#   |   2   | |   1   |
#   +-------+ +-------+
#              +-----+
#              |  3  |
#              +-----+
#
#   1: Samsung UR55
#   2: Samsung UR55
#   3: VB laptop
#
#+end_src
#+begin_src conf :noweb-ref sway-output-hvb1
set $primary   HDMI-A-1
set $secondary DP-1
set $laptop    eDP-1
#+end_src
*** Set resolution
Since scale of output #0 is 1.4, the position offset is:
  - secondary screen [H]: 3840/1.4 = 2742
  - laptop [H]: 3840/1.4 - 1920 = 411
  - laptop [V]: 2160/1.4 = 1542

#+begin_src conf :noweb-ref sway-output-hvb1
output $primary   mode 3840x2160@60hz position      0,0 scale 1.4
output $secondary mode 3840x2160@60hz position  -2742,0 scale 1.4
output $laptop    mode 1920x1080@60hz position 411,1542 scale 1
#+end_src
** Hub Viva-Bem 2
*** Set order
#+begin_src comment :tangle no
# Outputs:
#
#           +---------+ +---------+
#           |         | |         |
#  +-----+  |    1    | |    2    |
#  |  3  |  |         | |         |
#  +-----+  +---------+ +---------+
#
#   1: Samsung UR55
#   2: Samsung UR55
#   3: VB laptop
#
#+end_src
#+begin_src conf :noweb-ref sway-output-hvb2
set $primary   HDMI-A-1
set $secondary DP-1
set $laptop    eDP-1
#+end_src
*** Set resolution
Since scale of output #0 is 1.4, the position offset is:
  - secondary screen [H]: 3840/1.4 = 2742
  - laptop [H]: 3840/1.4 - 1920 = 411
  - laptop [V]: 2160/1.4 = 1542

#+begin_src conf :noweb-ref sway-output-hvb2
output $primary   mode 3840x2160@60hz position     0,0 scale 1.4
output $secondary mode 3840x2160@60hz position  2742,0 scale 1.4
output $laptop    mode 1920x1080@60hz position -1920,0 scale 1
#+end_src
** Duplicated cursor
https://github.com/swaywm/sway/issues/1666
For HDMI 4K@60Hz:
#+begin_src conf :noweb-ref sway-output-mirror
output HDMI-A-1 mode 3840x2160@60hz position 0,0
#+end_src

For USB-C 4K@60Hz:
#+begin_src conf :noweb-ref sway-output-mirror
output DP-1 mode 3840x2160@60hz position 0,0
#+end_src
** Tangle :noexport:
*** i3
The outputs settings are being managed by the display manager (e.g.: LightDM, SDDM) instead of the window manager.
#+begin_src conf :noweb yes :tangle _config_i3
<<i3-output-default>>
#<<i3-output-xrandr>>
#+end_src
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<sway-output-default>>
#<<sway-output-msc>>
#<<sway-output-hvb1>>
#<<sway-output-hvb2>>
#<<sway-output-mirror>>
#+end_src
* Workspaces definition
** Default output
*** Primary output
#+begin_src conf :noweb-ref ws
workspace "1:1" output $primary
workspace "2:2" output $primary
workspace "3:3" output $primary
workspace "4:4" output $primary
workspace "5:5" output $primary
workspace "6:6" output $primary
workspace "7:7" output $primary
workspace "8:8" output $primary
workspace "9:9" output $primary
workspace "10:0" output $primary
#+end_src
*** Secondary output
#+begin_src conf :noweb-ref ws
workspace "11:11" output $secondary
workspace "12:12" output $secondary
workspace "13:13" output $secondary
workspace "14:14" output $secondary
workspace "15:15" output $secondary
workspace "16:16" output $secondary
workspace "17:17" output $secondary
workspace "18:18" output $secondary
workspace "19:19" output $secondary
workspace "20:10" output $secondary
#+end_src
*** Tertiary output
#+begin_src conf :noweb-ref ws
workspace "21:21" output $tertiary
workspace "22:22" output $tertiary
workspace "23:23" output $tertiary
workspace "24:24" output $tertiary
workspace "25:25" output $tertiary
workspace "26:26" output $tertiary
workspace "27:27" output $tertiary
workspace "28:28" output $tertiary
workspace "29:29" output $tertiary
workspace "30:20" output $tertiary
#+end_src
** WS names (icons)
*** Primary monitor
#+begin_src conf :tangle no
set $ws1 "1 "
set $ws2 "2 "
set $ws3 "3 "
set $ws4 "4 "
set $ws5 "5 "
set $ws6 "6 "
set $ws7 "7 "
set $ws8 "8 "
set $ws9 "9 "
set $ws0 "10 "
set $ws0 "10 "
#+end_src
*** Secondary monitor
#+begin_src conf :tangle no
set $ws11 "11 "
set $ws12 "12 "
set $ws13 "13 "
set $ws14 "14 "
set $ws15 "15 "
set $ws16 "16 "
set $ws17 "17 "
set $ws18 "18 "
set $ws19 "19 J"
set $ws10 "20 E"
#+end_src
** WS names
*** Primary monitor
#+begin_src conf :noweb-ref ws
set $ws1 "1:1"
set $ws2 "2:2"
set $ws3 "3:3"
set $ws4 "4:4"
set $ws5 "5:5"
set $ws6 "6:6"
set $ws7 "7:7"
set $ws8 "8:8"
set $ws9 "9:9"
set $ws0 "10:0"
#+end_src
*** Secondary monitor
#+begin_src conf :noweb-ref ws
set $ws11 "11:11"
set $ws12 "12:12"
set $ws13 "13:13"
set $ws14 "14:14"
set $ws15 "15:15"
set $ws16 "16:16"
set $ws17 "17:17"
set $ws18 "18:18"
set $ws19 "19:19"
set $ws10 "20:10"
#+end_src
*** Tertiary monitor
#+begin_src conf :noweb-ref ws
set $ws21 "21:21"
set $ws22 "22:22"
set $ws23 "23:23"
set $ws24 "24:24"
set $ws25 "25:25"
set $ws26 "26:26"
set $ws27 "27:27"
set $ws28 "28:28"
set $ws29 "29:29"
set $ws20 "30:20"
#+end_src
** Tangle :noexport:
*** i3
#+begin_src conf :noweb yes :tangle _config_i3
<<ws>>
#+end_src
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<ws>>
#+end_src
* i3bang: raw section (beginning)
Make keybinds reusable in other modes (like inheritance).
Check https://github.com/tckmn/i3bang for more details.
#+begin_src conf :noweb-ref i3bang-begin
#!nobracket
!@<+default_keybindings
#+end_src
** Tangle :noexport:
*** i3
#+begin_src conf :noweb yes :tangle _config_i3
<<i3bang-begin>>
#+end_src
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<i3bang-begin>>
#+end_src
* Media control
** Playerctl
#+begin_src conf :noweb-ref playerctl
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPlay exec playerctl play-pause
bindsym XF86AudioPause exec playerctl play-pause
bindsym XF86AudioPrev exec playerctl previous
#+end_src
** Volume control
Use pactl to adjust volume in PulseAudio.
#+begin_src conf :tangle no
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl list sinks | grep 'Sink #' | grep -o '[0-9]*' | xargs -i pactl set-sink-volume {} +5% && pkill -RTMIN+1 i3blocks
bindsym XF86AudioLowerVolume exec --no-startup-id pactl list sinks | grep 'Sink #' | grep -o '[0-9]*' | xargs -i pactl set-sink-volume {} -5% && pkill -RTMIN+1 i3blocks
bindsym XF86AudioMute exec --no-startup-id pactl list sinks | grep 'Sink #' | grep -o '[0-9]*' | xargs -i pactl set-sink-mute {} toggle && pkill -RTMIN+1 i3blocks
bindsym XF86AudioMicMute exec --no-startup-id pactl list sources | grep 'Source #' | grep -o '[0-9]*' | xargs -i pactl set-sink-mute {} toggle && pkill -RTMIN+1 i3blocks
#+end_src
*** Volume
Volume up/down coarse.
#+begin_src conf :noweb-ref volume
bindsym XF86AudioRaiseVolume exec --no-startup-id amixer -q sset Master 5%+
bindsym XF86AudioLowerVolume exec --no-startup-id amixer -q sset Master 5%-
#+end_src

Volume up/down fine.
#+begin_src conf :noweb-ref volume
bindsym F15 exec --no-startup-id amixer -q sset Master 1%-
bindsym ctrl+F15 exec --no-startup-id amixer -q sset Master 1%+
#+end_src

Mute/unmute audio.
#+begin_src conf :noweb-ref volume
bindsym XF86AudioMute exec --no-startup-id amixer -q sset Master toggle
#+end_src

Set volume to 50%.
#+begin_src conf :noweb-ref volume
bindsym $mod+F15 exec --no-startup-id amixer -q sset Master 50%
#+end_src
** Microphone control
Mic volume up/down coarse.
#+begin_src conf :noweb-ref microphone
bindsym F14      exec --no-startup-id amixer -q sset Capture 5%-
bindsym ctrl+F14 exec --no-startup-id amixer -q sset Capture 5%+
#+end_src

Mic volume up/down fine.
#+begin_src conf :noweb-ref microphone
bindsym shift+F14      exec --no-startup-id amixer -q sset Capture 1%-
bindsym ctrl+shift+F14 exec --no-startup-id amixer -q sset Capture 1%+
#+end_src

Set mic volume to 50%.
#+begin_src conf :noweb-ref microphone
bindsym $mod+F14 exec --no-startup-id amixer -q sset Capture 50%
#+end_src

Mute/unmute mic.
#+begin_src conf :noweb-ref microphone
bindsym XF86AudioMicMute exec --no-startup-id amixer -q sset Capture toggle
bindsym shift+$mod+F14 exec --no-startup-id amixer -q sset Capture toggle
#+end_src
** Tangle :noexport:
*** i3
#+begin_src conf :noweb yes :tangle _config_i3
<<playerctl>>
<<microphone>>
<<volume>>
#+end_src
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<playerctl>>
<<microphone>>
<<volume>>
#+end_src
* Opacity
** i3
Windows transparency/opacity can be achieved with picom:
https://github.com/yshui/picom
*** Current window
#+begin_src conf :noweb-ref i3-opacity
#+end_src
*** All windows
#+begin_src conf :noweb-ref i3-opacity
#+end_src
*** Enable transparency
#+begin_src conf :noweb-ref i3-opacity
#+end_src
** Sway
Windows transparency/opacity can be achieved with the inactive-windows-transparency.py script:
https://github.com/OctopusET/sway-contrib
*** Current window
#+begin_src conf :noweb-ref sway-opacity
bindsym F19      exec --no-startup-id pkill -f inactive-windows-transparency; exec "$SCRIPT_PATH/opacity.sh current dec"
bindsym ctrl+F19 exec --no-startup-id pkill -f inactive-windows-transparency; exec "$SCRIPT_PATH/opacity.sh current inc"
#+end_src
*** All windows
#+begin_src conf :noweb-ref sway-opacity
bindsym shift+F19      exec --no-startup-id pkill -f inactive-windows-transparency; exec "$SCRIPT_PATH/opacity.sh all dec"
bindsym shift+ctrl+F19 exec --no-startup-id pkill -f inactive-windows-transparency; exec "$SCRIPT_PATH/opacity.sh all inc"
#+end_src
*** Enable transparency
#+begin_src conf :noweb-ref sway-opacity
bindsym $mod+F19 exec --no-startup-id pkill -f inactive-windows-transparency; exec "/usr/share/sway-contrib/inactive-windows-transparency.py --opacity 0.85 &"
#+end_src
** Tangle :noexport:
*** i3
#+begin_src conf :noweb yes :tangle _config_i3
<<i3-opacity>>
#+end_src
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<sway-opacity>>
#+end_src
* Window settings
** Change focus
Deprecated. Moved to xremap (and Emacs) config.
*** i3
#+begin_src conf :noweb-ref i3-change-focus
#bindsym $mod+Left  focus left;  exec "$SCRIPT_PATH/mouse-warp.sh"
#bindsym $mod+Down  focus down;  exec "$SCRIPT_PATH/mouse-warp.sh"
#bindsym $mod+Up    focus up;    exec "$SCRIPT_PATH/mouse-warp.sh"
#bindsym $mod+Right focus right; exec "$SCRIPT_PATH/mouse-warp.sh"
#+end_src
*** Sway
#+begin_src conf :noweb-ref sway-change-focus
#bindsym $mod+Left  focus left
#bindsym $mod+Down  focus down
#bindsym $mod+Up    focus up
#bindsym $mod+Right focus right
#+end_src
** Move window
#+begin_src conf :noweb-ref window-settings
bindsym $mod+Shift+Left  move left
bindsym $mod+Shift+Down  move down
bindsym $mod+Shift+Up    move up
bindsym $mod+Shift+Right move right
#+end_src
** Other focus
Change focus between tiling / floating windows
#+begin_src conf :tangle no
bindsym $mod+space focus mode_toggle
#+end_src

Focus the parent container
#+begin_src conf :tangle no
bindsym $mod+a focus parent
#+end_src

Focus the child container
#+begin_src conf :tangle no
bindsym $mod+d focus child
#+end_src

Switch to latest urgent window
#+begin_src conf :tangle no
bindsym $mod+z [urgent=latest] focus
#+end_src
** General
*** Split
Split window in horizontal/vertical orientation
#+begin_src conf :noweb-ref window-settings
bindsym mod1+h split toggle
#bindsym mod1+h split h
#bindsym mod1+v split v
#+end_src
*** Container layout
Change container layout (stacked, tabbed, toggle split).
#+begin_src conf :noweb-ref window-settings
bindsym mod1+$mod+e layout toggle stacked tabbed
#+end_src
*** Fullscreen
Enter fullscreen mode for the focused container.
#+begin_src conf :noweb-ref window-settings
#bindsym mod1+$mod+f fullscreen toggle
bindsym Shift+mod1+$mod+f fullscreen toggle
#+end_src
*** Tiling/Floating
Toggle between tiling/floating window.
#+begin_src conf :noweb-ref window-settings
bindsym mod1+$mod+d floating toggle
#+end_src
*** Kill window
Kill focused window, unless it's a scratchpad. Check the [[https://github.com/ito-rafael/dotfiles/blob/master/scripts/hide-or-kill.sh][hide-or-kill.sh]] script for more details.
#+begin_src conf :noweb-ref window-settings
#bindsym mod1+$mod+q exec $SCRIPT_PATH/hide-or-kill.sh
bindsym shift+mod1+$mod+q exec $SCRIPT_PATH/kill-window.sh
#+end_src
** Tangle :noexport:
*** i3
#+begin_src conf :noweb yes :tangle _config_i3
<<i3-change-focus>>
<<window-settings>>
#+end_src
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<sway-change-focus>>
<<window-settings>>
#+end_src
* Restart i3/sway
** i3
*** Reload
#+begin_src conf :noweb-ref i3-restart
bindsym mod1+$mod+s exec ~/.config/i3/i3bang.rb; reload
#+end_src
*** Restart
#+begin_src conf :noweb-ref i3-restart
bindsym mod1+$mod+c exec ~/.config/i3/i3bang.rb; restart
#+end_src
*** Exit
Exit i3 (logs you out of your X session)
#+begin_src conf :noweb-ref i3-restart
bindsym mod1+$mod+x exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"
#+end_src
** Sway
Restart Sway inplace (preserves your layout/session, can be used to upgrade Sway)
*** Reload/"Restart"
#+begin_src conf :noweb-ref sway-restart
bindsym mod1+$mod+c exec ~/.config/sway/i3bang.rb; reload
#+end_src
*** Exit
Exit Sway (logs you out of your session)
#+begin_src conf :noweb-ref sway-restart
bindsym mod1+$mod+x exec "swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit Sway? This will end your session.' -B 'Yes, exit Sway' 'swaymsg exit'"
#+end_src
** Tangle :noexport:
*** i3
#+begin_src conf :noweb yes :tangle _config_i3
<<i3-restart>>
#+end_src
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<sway-restart>>
#+end_src
* Workspaces navigation
** Switch to workspace
Navigate to workspace and check if there is any window opened there:
  - if there is a window:
    - simply navigate to the workspace
  - if empty:
    - navigate to the workspace
    - restore its layout
    - open windows
*** Primary monitor
#+begin_src conf :noweb-ref ws-navigation
bindsym $mod+1 exec "$SCRIPT_PATH/navigate2ws.sh 1"
bindsym $mod+2 exec "$SCRIPT_PATH/navigate2ws.sh 2"
bindsym $mod+3 exec "$SCRIPT_PATH/navigate2ws.sh 3"
bindsym $mod+4 exec "$SCRIPT_PATH/navigate2ws.sh 4"
bindsym $mod+5 exec "$SCRIPT_PATH/navigate2ws.sh 5"
bindsym $mod+6 exec "$SCRIPT_PATH/navigate2ws.sh 6"
bindsym $mod+7 exec "$SCRIPT_PATH/navigate2ws.sh 7"
bindsym $mod+8 exec "$SCRIPT_PATH/navigate2ws.sh 8"
bindsym $mod+9 exec "$SCRIPT_PATH/navigate2ws.sh 9"
bindsym $mod+0 exec "$SCRIPT_PATH/navigate2ws.sh 0"
#+end_src
*** Secondary monitor
#+begin_src conf :noweb-ref ws-navigation
bindsym shift+$mod+1 exec "$SCRIPT_PATH/navigate2ws.sh 11"
bindsym shift+$mod+2 exec "$SCRIPT_PATH/navigate2ws.sh 12"
bindsym shift+$mod+3 exec "$SCRIPT_PATH/navigate2ws.sh 13"
bindsym shift+$mod+4 exec "$SCRIPT_PATH/navigate2ws.sh 14"
bindsym shift+$mod+5 exec "$SCRIPT_PATH/navigate2ws.sh 15"
bindsym shift+$mod+6 exec "$SCRIPT_PATH/navigate2ws.sh 16"
bindsym shift+$mod+7 exec "$SCRIPT_PATH/navigate2ws.sh 17"
bindsym shift+$mod+8 exec "$SCRIPT_PATH/navigate2ws.sh 18"
bindsym shift+$mod+9 exec "$SCRIPT_PATH/navigate2ws.sh 19"
bindsym shift+$mod+0 exec "$SCRIPT_PATH/navigate2ws.sh 10"
#+end_src
*** Tertiary monitor
#+begin_src conf :noweb-ref ws-navigation
bindsym mod3+1 exec "$SCRIPT_PATH/navigate2ws.sh 21"
bindsym mod3+2 exec "$SCRIPT_PATH/navigate2ws.sh 22"
bindsym mod3+3 exec "$SCRIPT_PATH/navigate2ws.sh 23"
bindsym mod3+4 exec "$SCRIPT_PATH/navigate2ws.sh 24"
bindsym mod3+5 exec "$SCRIPT_PATH/navigate2ws.sh 25"
bindsym mod3+6 exec "$SCRIPT_PATH/navigate2ws.sh 26"
bindsym mod3+7 exec "$SCRIPT_PATH/navigate2ws.sh 27"
bindsym mod3+8 exec "$SCRIPT_PATH/navigate2ws.sh 28"
bindsym mod3+9 exec "$SCRIPT_PATH/navigate2ws.sh 29"
bindsym mod3+0 exec "$SCRIPT_PATH/navigate2ws.sh 20"
#+end_src
** Move container to WS
*** Primary monitor
#+begin_src conf :noweb-ref ws-navigation
bindsym ctrl+$mod+1 move container to workspace number $ws1; workspace $ws1
bindsym ctrl+$mod+2 move container to workspace number $ws2; workspace $ws2
bindsym ctrl+$mod+3 move container to workspace number $ws3; workspace $ws3
bindsym ctrl+$mod+4 move container to workspace number $ws4; workspace $ws4
bindsym ctrl+$mod+5 move container to workspace number $ws5; workspace $ws5
bindsym ctrl+$mod+6 move container to workspace number $ws6; workspace $ws6
bindsym ctrl+$mod+7 move container to workspace number $ws7; workspace $ws7
bindsym ctrl+$mod+8 move container to workspace number $ws8; workspace $ws8
bindsym ctrl+$mod+9 move container to workspace number $ws9; workspace $ws9
bindsym ctrl+$mod+0 move container to workspace number $ws0; workspace $ws0
#+end_src
*** Secondary monitor
#+begin_src conf :noweb-ref ws-navigation
bindsym shift+ctrl+$mod+1 move container to workspace number $ws11; workspace $ws11
bindsym shift+ctrl+$mod+2 move container to workspace number $ws12; workspace $ws12
bindsym shift+ctrl+$mod+3 move container to workspace number $ws13; workspace $ws13
bindsym shift+ctrl+$mod+4 move container to workspace number $ws14; workspace $ws14
bindsym shift+ctrl+$mod+5 move container to workspace number $ws15; workspace $ws15
bindsym shift+ctrl+$mod+6 move container to workspace number $ws16; workspace $ws16
bindsym shift+ctrl+$mod+7 move container to workspace number $ws17; workspace $ws17
bindsym shift+ctrl+$mod+8 move container to workspace number $ws18; workspace $ws18
bindsym shift+ctrl+$mod+9 move container to workspace number $ws19; workspace $ws19
bindsym shift+ctrl+$mod+0 move container to workspace number $ws10; workspace $ws10
#+end_src
*** Tertiary monitor
#+begin_src conf :noweb-ref ws-navigation
bindsym ctrl+mod3+0 move container to workspace number $ws20; workspace $ws20
bindsym ctrl+mod3+1 move container to workspace number $ws21; workspace $ws21
bindsym ctrl+mod3+2 move container to workspace number $ws22; workspace $ws22
bindsym ctrl+mod3+3 move container to workspace number $ws23; workspace $ws23
bindsym ctrl+mod3+4 move container to workspace number $ws24; workspace $ws24
bindsym ctrl+mod3+5 move container to workspace number $ws25; workspace $ws25
bindsym ctrl+mod3+6 move container to workspace number $ws26; workspace $ws26
bindsym ctrl+mod3+7 move container to workspace number $ws27; workspace $ws27
bindsym ctrl+mod3+8 move container to workspace number $ws28; workspace $ws28
bindsym ctrl+mod3+9 move container to workspace number $ws29; workspace $ws29
#+end_src
** Navigate on same monitor
#+begin_src conf :noweb-ref ws-navigation
bindsym shift+mod3+Down workspace next_on_output
bindsym shift+mod3+Up  workspace prev_on_output
#+end_src
** Navigate among monitors
#+begin_src conf :noweb-ref ws-navigation
bindsym shift+mod3+Left  focus output left
bindsym Ctrl+$mod+Left   focus output left
bindsym shift+mod3+Right focus output right
bindsym Ctrl+$mod+Right  focus output right
#+end_src
** Move container among monitors
*** Arrows
#+begin_src conf :noweb-ref ws-navigation
bindsym $mod+shift+mod3+Left  move container to output left;  focus output left
bindsym $mod+shift+mod3+Right move container to output right; focus output right
#+end_src
*** Numbers
#+begin_src conf :noweb-ref ws-navigation
bindsym ctrl+mod1+1 move workspace to output $primary;   focus output $primary
bindsym ctrl+mod1+2 move workspace to output $secondary; focus output $secondary
bindsym ctrl+mod1+3 move workspace to output $tertiary;  focus output $tertiary
#+end_src
** Tangle :noexport:
*** i3
#+begin_src conf :noweb yes :tangle _config_i3
<<ws-navigation>>
#+end_src
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<ws-navigation>>
#+end_src
* Custom keybindings
** Applications
#+begin_src conf :noweb-ref keybindings
#bindsym $mod+b exec firefox
#bindsym $mod+c exec chromium
#bindsym $mod+n exec thunar
#bindsym $mod+l exec lollypop
#bindsym $mod+e exec thunderbird
#bindsym $mod+g exec kitty ranger
#bindsym $mod+p exec spotify --force-device-scale-factor=2 # shortcut to open Spotify
#+end_src
** Terminal
#+begin_src conf :noweb-ref keybindings
bindsym $mod+t exec kitty
#bindsym mod1+$mod+t exec kitty
#bindsym $mod+t exec i3-sensible-terminal
#bindsym mod1+$mod+t exec i3-sensible-terminal
#bindsym ctrl+$mod+t exec i3-sensible-terminal
#+end_src
** Brightness
*** xbacklight
#+begin_src conf :tangle no
bindsym XF86MonBrightnessUp   exec --no-startup-id xbacklight -inc 5
bindsym XF86MonBrightnessDown exec --no-startup-id xbacklight -dec 5
#+end_src
*** brightnessctl
#+begin_src conf :noweb-ref keybindings
bindsym XF86MonBrightnessDown exec brightnessctl set 5%-
bindsym XF86MonBrightnessUp exec brightnessctl set 5%+
#+end_src
** Rofi
#+begin_src conf :noweb-ref rofi
bindsym $mod+Return       exec "$SCRIPT_PATH/rofi.sh drun"
bindsym Shift+$mod+Return exec "$SCRIPT_PATH/rofi.sh ssh"
bindsym Ctrl+$mod+Return  exec "$SCRIPT_PATH/rofi.sh window"
bindsym $alt+$mod+Return  exec "$SCRIPT_PATH/rofi.sh run"
#+end_src
** Screenshot
*** i3
#+begin_src conf :noweb-ref i3-screenshot
bindsym Print exec shutter
#+end_src
*** Sway
#+begin_src conf :noweb-ref sway-screenshot
bindsym Print exec grim
bindsym shift+Print exec 'grim -g "$(slurp)"'
bindsym ctrl+Print exec 'grim -g "$(slurp)" - | swappy -f -'
#+end_src
** OBS
#+begin_src conf :noweb-ref keybindings
bindsym shift+$alt+F1 exec "$SCRIPT_PATH/obs-tools.py --scene camera"
bindsym shift+$alt+F2 exec "$SCRIPT_PATH/obs-tools.py --scene presentation"
bindsym shift+$alt+F3 exec "$SCRIPT_PATH/obs-tools.py --scene scene-3"
bindsym shift+$alt+F4 exec "$SCRIPT_PATH/obs-tools.py --scene scene-4"
bindsym shift+$alt+F5 exec "$SCRIPT_PATH/obs-tools.py --scene scene-5"
bindsym shift+$alt+F6 exec "$SCRIPT_PATH/obs-tools.py --scene scene-6"
bindsym shift+$alt+F7 exec "$SCRIPT_PATH/obs-tools.py --scene scene-7"
bindsym shift+$alt+F8 exec "$SCRIPT_PATH/obs-tools.py --scene scene-8"
bindsym shift+$alt+F9 exec "$SCRIPT_PATH/obs-tools.py --scene scene-9"
bindsym shift+$alt+F10 exec "$SCRIPT_PATH/obs-tools.py --scene output-0"
bindsym shift+$alt+F11 exec "$SCRIPT_PATH/obs-tools.py --scene output-1"
bindsym shift+$alt+F12 exec "$SCRIPT_PATH/obs-tools.py --scene output-2"
bindsym shift+$alt+F14 exec "$SCRIPT_PATH/obs-tools.py --record"
#+end_src
** Window properties
Save window properties into "/tmp/window_prop.tmp" file.
*** i3
#+begin_src conf :noweb-ref i3-xprop
bindsym $alt+ctrl+n exec i3-msg -t get_tree | jq -re '.. | select(type == "object") | select(.focused)' > /tmp/window_prop.tmp
#+end_src
*** Sway
#+begin_src conf :noweb-ref sway-wlprop
bindsym $alt+ctrl+n exec "$SCRIPT_PATH/wlprop.sh focused"
#+end_src
** Tangle :noexport:
*** i3
#+begin_src conf :noweb yes :tangle _config_i3
<<keybindings>>
<<rofi>>
<<i3-screenshot>>
<<i3-xprop>>
#+end_src
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<keybindings>>
<<rofi>>
<<sway-screenshot>>
<<sway-wlprop>>
#+end_src
* Logitech MX
** Change host
Change host for MX Keys and MX Master 3.
#+begin_src conf :tangle no
#bindsym F13 exec /home/rafael/mx_script.sh
bindsym --release F20 exec $SCRIPT_PATH/mx_script.sh
#+end_src
** MX Master 3
*** Copy
"copy" shortcut: "i" button + down gesture.
#+begin_src conf :tangle no
bindsym XF86Copy [class="Xfce4-terminal"] exec "xdotool keydown ctrl keydown shift keydown c keyup ctrl keyup shift keyup c"; exec "sleep 0.1"
#+end_src
*** Paste
"paste" shortcut: "i" button + up gesture.
#+begin_src conf :tangle no
bindsym XF86Paste [class="Xfce4-terminal"] exec "xdotool keydown ctrl keydown shift keydown v keyup ctrl keyup shift keyup v"; exec "sleep 0.1"
#+end_src
** MX Keys
Workaround to open terminal.
#+begin_src conf :tangle no
bindsym ctrl+space exec i3-sensible-terminal
#+end_src
* Mouse keybindings
** Volume control
*** i3
Use button9 + scroll to control volume.
  --> button9 is mapped as Super_R using the interception tool, which is mapped as mod3 using xmodmap.
#+begin_src conf :tangle no
bindsym mod3+ --whole-window button4 exec "pactl set-sink-volume @DEFAULT_SINK@ +5% && pkill -RTMIN+10 i3blocks"
bindsym mod3+ --whole-window button5 exec "pactl set-sink-volume @DEFAULT_SINK@ -5% && pkill -RTMIN+10 i3blocks"
#+end_src

#+begin_src conf :noweb-ref mouse-keybindings
bindsym --whole-window Shift+button4 exec --no-startup-id amixer -q sset Master 1%+
bindsym --whole-window Shift+button5 exec --no-startup-id amixer -q sset Master 1%-
#+end_src
** Mouse keys
*** Sway
**** Cursor
| key | cursor movement |
|-----+-----------------|
| kp4 | left            |
| kp2 | down            |
| kp8 | up              |
| kp6 | right           |
#+begin_src conf :noweb-ref sway-mouse-keybindings
bindsym kp_4 seat - cursor move -10  0
bindsym kp_2 seat - cursor move  0   10
bindsym kp_8 seat - cursor move  0  -10
bindsym kp_6 seat - cursor move  10  0
#+end_src
**** Buttons
| key | mouse button |
|-----+--------------|
| kp/ | left click   |
| kp* | middle click |
| kb- | right click  |
#+begin_src conf :noweb-ref sway-mouse-keybindings
bindsym kp_divide   seat - cursor press button1
bindsym kp_multiply seat - cursor press button2
bindsym kp_subtract seat - cursor press button3
#+end_src
**** Wheel
| key | wheel movement |
|-----+----------------|
| kp1 | up             |
| kp3 | down           |
| kp7 | right          |
| kp9 | left           |
#+begin_src conf :noweb-ref sway-mouse-keybindings
bindsym kp_1 seat - cursor press button4
bindsym kp_3 seat - cursor press button5
bindsym kp_7 seat - cursor press button6
bindsym kp_9 seat - cursor press button7
#+end_src
*** i3
**** Cursor
| key | cursor movement |
|-----+-----------------|
| kp4 | left            |
| kp2 | down            |
| kp8 | up              |
| kp6 | right           |
#+begin_src conf :noweb-ref i3-mouse-keybindings
#+end_src
**** Buttons
| key | mouse button |
|-----+--------------|
| kp/ | left click   |
| kp* | middle click |
| kb- | right click  |
#+begin_src conf :noweb-ref i3-mouse-keybindings
#+end_src
**** Wheel
| key | wheel movement |
|-----+----------------|
| kp9 | left           |
| kp3 | down           |
| kp1 | up             |
| kp7 | right          |
#+begin_src conf :noweb-ref i3-mouse-keybindings
#+end_src
** Tangle :noexport:
*** i3
#+begin_src conf :noweb yes :tangle _config_i3
<<i3-mouse-keybindings>>
#+end_src
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<sway-mouse-keybindings>>
#+end_src
* Rotate screen
** Portrait
- rotate screen
- rotate touchscreen
- disable touchpad
- disable touchpad click
#+begin_src conf :noweb-ref rotate-screen
bindsym mod1+$mod+Up exec "\
    echo 'rotate screen' &&\
    xrandr --output eDP-1 --rotate left &&\
    echo 'rotate touchscreen' &&\
    xinput set-prop ELAN\ Touchscreen --type=float 'Coordinate Transformation Matrix'  0 -1 1 1 0 0 0 0 1 &&\
    echo 'disable touchpad' &&\
    synclient TouchpadOff=1 &&\
    echo 'disable touchpad click' &&\
    synclient RightButtonAreaLeft=0 &&\
    synclient RightButtonAreaTop=0 \
"
#+end_src
** Landscape
- rotate screen
- rotate touchscreen
- enable touchpad
- enable touchpad click
#+begin_src conf :noweb-ref rotate-screen
bindsym mod1+$mod+Down exec "\
    echo 'rotate screen' &&\
    xrandr --output eDP-1 --rotate normal && \
    echo 'rotate touchscreen' &&\
    xinput set-prop ELAN\ Touchscreen --type=float 'Coordinate Transformation Matrix'  0  0 0 0 0 0 0 0 0 &&\
    echo 'enable touchpad' &&\
    synclient TouchpadOff=0 &&\
    echo 'enable touchpad click' &&\
    synclient RightButtonAreaLeft=3472 &&\
    synclient RightButtonAreaTop=4080 \
"
#+end_src
** Tangle :noexport:
*** i3
#+begin_src conf :noweb yes :tangle _config_i3
<<rotate-screen>>
#+end_src
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<rotate-screen>>
#+end_src
* i3bang: raw section (end)
End raw section: !@<+default_keybindings
#+begin_src conf :noweb-ref i3bang-end
>
#+end_src
** Tangle :noexport:
*** i3
#+begin_src conf :noweb yes :tangle _config_i3
<<i3bang-end>>
#+end_src
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<i3bang-end>>
#+end_src
* Modes
** System
*** Description
source:
https://wiki.archlinux.org/index.php/I3#Shutdown,_reboot,_lock_screen
*** i3
**** Locker & messanger
Adds 1 second delay to prevent possible race conditions with suspend.
#+begin_src conf :noweb-ref i3-mode-system
set $PATH_LOCKER $XDG_CONFIG_HOME/i3lock
set $locker $XDG_CONFIG_HOME/i3lock/lock-screen.sh
set $messenger i3-msg exit
#+end_src
**** Mode
Obs: the -i argument for systemctl poweroff causes a shutdown even if other users are logged-in (this requires polkit), or when logind (wrongly) assumes so.
#+begin_src conf :noweb-ref i3-mode-system
set $mode_system System: (s)hutdown, (r)eboot, (l)ock, (S)uspend, (h)ibernate, (e)xit/logout
#-----------------------------
mode "$mode_system" {
    bindsym l       exec --no-startup-id $locker,                         mode "default"
    bindsym h       exec --no-startup-id $locker && systemctl hibernate,  mode "default"
    bindsym Shift+s exec --no-startup-id $locker && systemctl suspend,    mode "default"
    bindsym e       exec --no-startup-id $PATH_LOCKER/del-screenshot.sh; exec --no-startup-id $messenger,            mode "default"
    bindsym r       exec --no-startup-id $PATH_LOCKER/del-screenshot.sh; exec --no-startup-id systemctl reboot,      mode "default"
    bindsym s       exec --no-startup-id $PATH_LOCKER/del-screenshot.sh; exec --no-startup-id systemctl poweroff -i, mode "default"
    #-----------------------------
    # back to normal: Enter or Escape
    bindsym Return    exec --no-startup-id $PATH_LOCKER/del-screenshot.sh; mode "default"
    bindsym Escape    exec --no-startup-id $PATH_LOCKER/del-screenshot.sh; mode "default"
    bindsym $mod+Home exec --no-startup-id $PATH_LOCKER/del-screenshot.sh; mode "default"
    #-----------------------------
    # inherent default keybinds (i3bang)
    !@default_keybindings
}
#+end_src
**** Keybinding
#+begin_src conf :noweb-ref i3-mode-system
bindsym $mod+Home exec --no-startup-id $PATH_LOCKER/take-screenshot.sh; mode "$mode_system"
#+end_src
*** Sway
**** Locker & messanger
#+begin_src conf :noweb-ref sway-mode-system
set $locker $XDG_CONFIG_HOME/swaylock/lock-screen.sh
set $messenger swaymsg exit
#+end_src
**** Mode
Obs: the -i argument for systemctl poweroff causes a shutdown even if other users are logged-in (this requires polkit), or when logind (wrongly) assumes so.
#+begin_src conf :noweb-ref sway-mode-system
set $mode_system System: (s)hutdown, (r)eboot, (l)ock, (S)uspend, (h)ibernate, (e)xit/logout
#-----------------------------
mode "$mode_system" {
    bindsym l       exec --no-startup-id $locker,                         mode "default"
    bindsym e       exec --no-startup-id $messenger,                      mode "default"
    bindsym Shift+s exec --no-startup-id $locker && systemctl suspend,    mode "default"
    bindsym h       exec --no-startup-id $locker && systemctl hibernate,  mode "default"
    bindsym r       exec --no-startup-id systemctl reboot,                mode "default"
    bindsym s       exec --no-startup-id systemctl poweroff -i,           mode "default"
    #-----------------------------
    # back to normal: Enter or Escape
    bindsym Return    mode "default"
    bindsym Escape    mode "default"
    bindsym $mod+Home mode "default"
    #-----------------------------
    # inherent default keybinds (i3bang)
    !@default_keybindings
}
#+end_src
**** Keybinding
#+begin_src conf :noweb-ref sway-mode-system
bindsym $mod+Home mode "$mode_system"
#+end_src
** Resize
*** Description
Resize window (you can also use the mouse for that)
  - These bindings trigger as soon as you enter the resize mode
  - Pressing left will shrink the window’s width.
  - Pressing right will grow the window’s width.
  - Pressing up will shrink the window’s height.
  - Pressing down will grow the window’s height.
*** Mode
#+begin_src conf :noweb-ref mode-resize
mode "resize" {
    #-----------------------------
    # colemak home row
    bindsym n resize shrink width  5 px or 5 ppt
    bindsym e resize shrink height 5 px or 5 ppt
    bindsym i resize grow   height 5 px or 5 ppt
    bindsym o resize grow   width  5 px or 5 ppt
    #-----------------------------
    # same bindings, but for the arrow keys
    bindsym Left  resize shrink width  5 px or 5 ppt
    bindsym Down  resize shrink height 5 px or 5 ppt
    bindsym Up    resize grow   height 5 px or 5 ppt
    bindsym Right resize grow   width  5 px or 5 ppt
    #-----------------------------
    # back to normal: Enter or Escape or $mod+r
    bindsym Return mode "default"
    bindsym Escape mode "default"
    bindsym mod1+$mod+r mode "default"
    #-----------------------------
    # inherent default keybinds (i3bang)
    !@default_keybindings
}
#+end_src
*** Keybinding
#+begin_src conf :noweb-ref mode-resize
bindsym mod1+$mod+r mode "resize"
#+end_src
** Number
*** Description
Edit top right keyboard keys to work as a numpad (for Lenovo Yoga 2 Pro)

+-------+-----------+---------+
| digit | key       | keycode |
+-------+-----------+---------+
|   1   | lum+      |   233   |
|   2   | PrtSc     |   107   |
|   3   | delete    |   119   |
|   4   | '+' & '=' |    21   |
|   5   | backspace |    22   |
|   6   | home      |   110   |
|   7   | '}' & ']' |    35   |
|   8   | '\' & '|' |    51   |
|   9   | End       |   115   |
|   0   | Enter     |    36   |
+-------+---+-------+---------+
| Backspace | PgUp  |   112   |
| Enter     | ' & " |    48   |
+-----------------------------+
*** Mode
#+begin_src conf :tangle no
mode "number" {
    #-----------------------------
    # exit "number" mode and load default Xmodmap file
    bindsym Escape mode "default"; exec "xmodmap ~/.Xmodmap";
    bindsym $mod+Next mode "default"; exec "xmodmap ~/.Xmodmap";
    #-----------------------------
    # test
    #bindsym Shift+A exec "i3-sensible-terminal";
    #-----------------------------
    # inherent default keybinds (i3bang)
    !@default_keybindings
}
#+end_src
*** Keybinding
Enter "number" mode and load Xmodmap file with number modifications
#+begin_src conf :tangle no
bindsym $mod+Next mode "number"; exec "xmodmap ~/.Xmodmap_numbers"
#+end_src
** Double-click (dc)
*** Description
Double-click (dc) mode makes (x2)button3 click close the current window.
*** Tests
#+begin_src conf :tangle no
# !!! TO BE IMPLEMENTED !!!
bindsym --whole-window button2 exec "xdotool key control+w"
bindsym --whole-window button2 exec "xdotool getwindowfocus windowkill"
bindsym --whole-window button2 exec 'xte "key XF86Close"'
#+end_src
*** Mode
#+begin_src conf :tangle no
# !!! TO BE IMPLEMENTED !!!
mode "dc" {
    # close window
    #bindsym --whole-window button3 exec kill
    bindsym --whole-window button3 exec "thunar"
    bindsym button1 mode "default"
    #-----------------------------
    # inherent default keybinds (i3bang)
    !@default_keybindings
}
#+end_src
*** Keybinding
#+begin_src conf :tangle no
# !!! TO BE IMPLEMENTED !!!
bindsym --whole-window button3 exec "i3-msg 'mode dc'; sleep 0.5; i3-msg 'mode default'"
bindsym --whole-window button3 exec "xdotool key 248 && i3-msg 'mode dc'; sleep 5; i3-msg 'mode default'"
bindsym --whole-window button3 exec "sleep 0.5 && xdotool key 248"
bindsym --whole-window button3 exec "i3-msg 'mode dc'; sleep 0.2; xdotool key Menu; i3-msg 'mode default'"
bindsym --whole-window button2 exec kill
#+end_src
** Presentation: Projecteur
*** Description
Mode to be used with a presentation pointer alongside with Projecteur software.
https://github.com/jahnf/Projecteur
*** Mode
#+begin_src conf :tangle no
mode "presentation" {
    # test
    # !!! TO BE IMPLEMENTED !!!
    # projecteur -c spot=toggle
    #-----------------------------
    # projecteur -c zoom=true
    # projecteur -c zoom=false
    #-----------------------------
    # projecteur -c zoom.factor=1.5
    # projecteur -c border.size=0
    # projecteur -c zoom.factor=20
    # projecteur -c border.size=100
    #-----------------------------
    # projecteur -c spot.size=5
    # projecteur -c spot.size=100
    #-----------------------------
    # projecteur -c border.color=red
    # projecteur -c border.color=green
    #-----------------------------
    # back to normal mode ($mod+P) and stop Projecteur
    bindsym mod1+p mode "default"; exec killall projecteur
    #-----------------------------
    # inherent default keybinds (i3bang)
    !@default_keybindings
}
#+end_src
*** Keybinding
Start "presentation" mode and run Projecteur
#+begin_src conf :tangle no
bindsym mod1+P mode "presentation"; exec projecteur -D 25a7:1047
#+end_src
** Presentation: pdfpc
*** Description
Mode to be used for presentations with OBS.
https://github.com/pdfpc/pdfpc
*** Mode
#+begin_src conf :noweb-ref mode-presentation-obs
mode "presentation-obs" {
    #-----------------------------
    # switch to scenes in OBS
    bindsym r exec "$SCRIPT_PATH/obs-tools.py --scene camera"
    bindsym s exec "$SCRIPT_PATH/obs-tools.py --scene presentation"
    bindsym t exec "$SCRIPT_PATH/obs-tools.py --scene scene-3"
    bindsym w exec "$SCRIPT_PATH/obs-tools.py --scene scene-4"
    bindsym f exec "$SCRIPT_PATH/obs-tools.py --scene scene-5"
    bindsym p exec "$SCRIPT_PATH/obs-tools.py --scene scene-6"
    bindsym x exec "$SCRIPT_PATH/obs-tools.py --scene scene-7"
    bindsym c exec "$SCRIPT_PATH/obs-tools.py --scene scene-8"
    bindsym d exec "$SCRIPT_PATH/obs-tools.py --scene scene-9"
    #-----------------------------
    bindsym q exec "$SCRIPT_PATH/obs-tools.py --scene output-0"
    bindsym a exec "$SCRIPT_PATH/obs-tools.py --scene output-1"
    bindsym z exec "$SCRIPT_PATH/obs-tools.py --scene output-2"
    #-----------------------------
    # back to normal
    bindsym shift+$alt+F13 mode "default"
    #-----------------------------
    # inherent default keybinds (i3bang)
    !@default_keybindings
}
#+end_src
*** Keybinding
Start "presentation-obs" mode.
#+begin_src conf :noweb-ref mode-presentation-obs
bindsym shift+$alt+F13 mode "presentation-obs"
#+end_src
** Studio
*** Description
Mode to be used with set of webcams (EyeCam, top-view webcam, etc).
video-script:
  - JZYZ:
    - create new virtual /dev/video9 device ("Flip JZYZ")
    - flip JZYZ vertically
    - set resolution to 1920x1080 @ 30 fps
    - select MJPEG as input format
    - select YUV420P as output format
    - remove autofocus
    - change sharpness to 6
  - EyeCam:
    - create new virtual /dev/video8 device ("Flip EyeCam")
    - flip EyeCam vertically
    - set resolution to 1920x1080 @ 30 fps
    - select MJPEG as input format
    - select YUV420P as output format
*** Mode
#+begin_src conf :tangle no
mode "studio" {
    # test
    # !!! TO BE IMPLEMENTED !!!
    # ...
    #-----------------------------
    # back to normal mode ($mod+O) and stop video-script
    bindsym $mod+o mode "default"; exec killall video-script
    #-----------------------------
    # inherent default keybinds (i3bang)
    !@default_keybindings
}
#+end_src
*** Keybinding
Start "studio" mode.
#+begin_src conf :tangle no
bindsym $mod+O mode "studio"; exec video-script
#+end_src
** Tangle :noexport:
*** i3
#+begin_src conf :noweb yes :tangle _config_i3
<<i3-mode-system>>
<<mode-resize>>
<<mode-obs>>
#+end_src
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<sway-mode-system>>
<<mode-resize>>
<<mode-obs>>
#+end_src
* Applications default WS
** Window property
*** i3
#+begin_src conf :noweb-ref i3-window-property
set $prop class
#+end_src
*** Sway
#+begin_src conf :noweb-ref sway-window-property
set $prop app_id
#+end_src
** Applications
| workspace | application | description          |
|-----------+-------------+----------------------|
|         4 | Thunderbird | Email client         |
|         5 | spreadsheet | LibreOffice          |
|         6 | Lutris      | Gaming               |
|         7 | Nicotine+   | P2P music            |
|         7 | Deluge      | BitTorrent           |
|         8 | Lollypop    | Music player (local) |
|         9 | Spotify     | Music player (web)   |
|        10 | Blueman     | Bluetooth manager    |
|        10 | pavucontrol | Volume control       |
Obs.: both i3/Sway uses "class" for Spotify client.
#+begin_src conf :noweb-ref window-property
assign [$prop="thunderbird"] → $ws4
assign [$prop="libreoffice"] → $ws5
assign [$prop="lutris"] → $ws6
assign [$prop="deluge"] → $ws7
assign [$prop="nicotine"] → $ws7
assign [$prop="lollypop"] → $ws8
for_window [class="Spotify"] move --no-auto-back-and-forth to workspace $ws9
assign [$prop="blueman-manager"] → $ws10
assign [$prop="pavucontrol"] → $ws10
#+end_src
** Window-specific
*** Tkinter
Floating window for Tkinter (Python GUI)
#+begin_src conf :noweb-ref window-property
for_window [$prop="Tk"] floating enable
for_window [$prop="Toplevel"] floating enable
#+end_src
*** yad (Yet Another Dialog)
Floating window for yad (dialogs)
**** i3
#+begin_src conf :noweb-ref i3-dialog
for_window [$prop="Yad"] floating enable
#+end_src
**** Sway
#+begin_src conf :noweb-ref sway-dialog
for_window [$prop="yad"] floating enable
#+end_src
*** Show Me The Key
Floating window for showmethekey screencast tool.
**** i3
#+begin_src conf :noweb-ref i3-screencast
for_window [$prop="showmethekey-gtk" title="Show Me The Key"] floating enable
#for_window [$prop="showmethekey-gtk" title="Floating Window - Show Me The Key"] floating enable
#for_window [$prop="showmethekey-gtk" title="Floating Window - Show Me The Key"] sticky enable
#+end_src
**** Sway
#+begin_src conf :noweb-ref sway-screencast
for_window [$prop="showmethekey-gtk"] {
    floating enable
    sticky enable
    resize set width 1920 height 100
    # x=0; y=(width - 200)
    move position 0 880
}
for_window [$prop="one.alynx.showmethekey"] floating enable
#+end_src
** Tangle :noexport:
*** i3
#+begin_src conf :noweb yes :tangle _config_i3
<<i3-window-property>>
<<window-property>>
<<i3-dialog>>
<<i3-screencast>>
#+end_src
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<sway-window-property>>
<<window-property>>
<<sway-dialog>>
<<sway-screencast>>
#+end_src
* Scratchpads
** WhatsApp Web (on Brave Beta)
*** i3
#+begin_src conf :noweb-ref i3-whatsapp
for_window [$prop="^Brave-browser-beta$" instance="^web.whatsapp.com$"] floating enable
for_window [$prop="^Brave-browser-beta$" instance="^web.whatsapp.com$"] move position center
for_window [$prop="^Brave-browser-beta$" instance="^web.whatsapp.com$"] move scratchpad
for_window [$prop="^Brave-browser-beta$" instance="^web.whatsapp.com$"] border pixel 5
exec --no-startup-id brave-beta --app=https://web.whatsapp.com
bindsym $mod+b exec "$SCRIPT_PATH/show-or-launch.sh web.whatsapp.com 0.6 0.9"
#+end_src
*** Sway
#+begin_src conf :noweb-ref sway-whatsapp
for_window [$prop="^brave-web.whatsapp.com__-Default$"] {
    floating enable
    move position center
    move scratchpad
    border pixel 5
}
exec --no-startup-id brave-beta --app=https://web.whatsapp.com
bindsym $mod+b exec "$SCRIPT_PATH/show-or-launch.sh brave-web.whatsapp.com__-Default 0.6 0.9"
#+end_src
** YouTube Music (on Brave Beta)
*** i3
#+begin_src conf :noweb-ref i3-yt-music
for_window [$prop="^Brave-browser-beta$" instance="^music.youtube.com$"] floating enable
for_window [$prop="^Brave-browser-beta$" instance="^music.youtube.com$"] move position center
for_window [$prop="^Brave-browser-beta$" instance="^music.youtube.com$"] move scratchpad
for_window [$prop="^Brave-browser-beta$" instance="^music.youtube.com$"] border pixel 5
exec --no-startup-id brave-beta --app=https://music.youtube.com
bindsym $mod+g exec "$SCRIPT_PATH/show-or-launch.sh music.youtube.com 0.9 0.9"
#+end_src
*** Sway
#+begin_src conf :noweb-ref sway-yt-music
for_window [$prop="^brave-music.youtube.com__-Default$"] {
    floating enable
    move position center
    move scratchpad
    border pixel 5
}
exec --no-startup-id brave-beta --app=https://music.youtube.com
bindsym $mod+g exec "$SCRIPT_PATH/show-or-launch.sh brave-music.youtube.com__-Default 0.9 0.9"
#+end_src
** scrcpy
#+begin_src conf :noweb-ref scratchpads
bindsym $mod+v exec "$SCRIPT_PATH/adb-mdns-scrcpy.sh"
for_window [title="^dropdown_scrcpy$" $prop="^scrcpy$"] floating enable
for_window [title="^dropdown_scrcpy$" $prop="^scrcpy$"] move position center
for_window [title="^dropdown_scrcpy$" $prop="^scrcpy$"] move scratchpad
for_window [title="^dropdown_scrcpy$" $prop="^scrcpy$"] border pixel 5
#+end_src
** Python
#+begin_src conf :noweb-ref scratchpads
for_window [$prop="^dropdown_python$"] floating enable
for_window [$prop="^dropdown_python$"] move position center
for_window [$prop="^dropdown_python$"] move scratchpad
for_window [$prop="^dropdown_python$"] border pixel 5
exec --no-startup-id kitty --class="dropdown_python" -o font_size=20 -o include=$XDG_CONFIG_HOME/kitty/themes/python.conf python -q
bindsym $mod+j exec "$SCRIPT_PATH/show-or-launch.sh dropdown_python 0.6 0.6"
#+end_src
** Terminal
#+begin_src conf :noweb-ref scratchpads
exec --no-startup-id kitty --class="dropdown_terminal" -o font_size=14 -o include=$XDG_CONFIG_HOME/kitty/themes/terminal.conf -o background_opacity=0.85
bindsym $mod+m exec "$SCRIPT_PATH/show-or-launch.sh dropdown_terminal 0.75 0.75"
for_window [$prop="^dropdown_terminal$"] floating enable
for_window [$prop="^dropdown_terminal$"] move position center
for_window [$prop="^dropdown_terminal$"] move scratchpad
for_window [$prop="^dropdown_terminal$"] border pixel 5
#+end_src
** ZSA Keymapp
*** i3
#+begin_src conf :noweb-ref i3-keymapp
for_window [$prop="^Keymapp$"] floating enable
for_window [$prop="^Keymapp$"] move position center
for_window [$prop="^Keymapp$"] move scratchpad
for_window [$prop="^Keymapp$"] border pixel 5
exec --no-startup-id /usr/bin/keymapp
bindsym $mod+k exec "$SCRIPT_PATH/show-or-launch.sh Keymapp 0.75 0.75"
#+end_src
*** Sway
#+begin_src conf :noweb-ref sway-keymapp
for_window [$prop="^keymapp$"] {
    floating enable
    move position center
    move scratchpad
    border pixel 5
}
exec --no-startup-id /usr/bin/keymapp
bindsym $mod+k exec "$SCRIPT_PATH/show-or-launch.sh keymapp 0.75 0.75"
#+end_src
** Temporary scratchpads
*** 1: comma
#+begin_src conf :noweb-ref scratchpads
exec --no-startup-id "rm /tmp/scratchpad_pid_1.tmp"
bindsym $mod+comma       exec "$SCRIPT_PATH/scratchpad-temp.sh 1 create-show"
bindsym shift+$mod+comma exec "$SCRIPT_PATH/scratchpad-temp.sh 1 detach"
bindsym ctrl+$mod+comma  exec "$SCRIPT_PATH/scratchpad-temp.sh 1 destroy"
#+end_src
*** 2: dot
#+begin_src conf :noweb-ref scratchpads
exec --no-startup-id "rm /tmp/scratchpad_pid_2.tmp"
bindsym $mod+period       exec "$SCRIPT_PATH/scratchpad-temp.sh 2 create-show"
bindsym shift+$mod+period exec "$SCRIPT_PATH/scratchpad-temp.sh 2 detach"
bindsym ctrl+$mod+period  exec "$SCRIPT_PATH/scratchpad-temp.sh 2 destroy"
#+end_src
*** 3: slash
#+begin_src conf :noweb-ref scratchpads
exec --no-startup-id "rm /tmp/scratchpad_pid_3.tmp"
bindsym $mod+slash       exec "$SCRIPT_PATH/scratchpad-temp.sh 3 create-show"
bindsym shift+$mod+slash exec "$SCRIPT_PATH/scratchpad-temp.sh 3 detach"
bindsym ctrl+$mod+slash  exec "$SCRIPT_PATH/scratchpad-temp.sh 3 destroy"
#+end_src
** Tangle :noexport:
*** i3
#+begin_src conf :noweb yes :tangle _config_i3
<<scratchpads>>
<<i3-whatsapp>>
<<i3-yt-music>>
<<i3-keymapp>>
#+end_src
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<scratchpads>>
<<sway-whatsapp>>
<<sway-yt-music>>
<<sway-keymapp>>
#+end_src
* VPN
** La Casa Nostra
#+begin_src conf :noweb-ref vpn
bindsym $alt+$mod+1 exec "$SCRIPT_PATH/vpn-connecter.sh lcn toggle"
exec --no-startup-id "rm /tmp/vpn_lcn.tmp"
#+end_src
** Unicamp
#+begin_src conf :noweb-ref vpn
bindsym $alt+$mod+2 exec "$SCRIPT_PATH/vpn-connecter.sh unicamp toggle"
exec --no-startup-id "rm /tmp/vpn_unicamp.tmp"
#+end_src
** LBiC
#+begin_src conf :noweb-ref vpn
bindsym $alt+$mod+3 exec "$SCRIPT_PATH/vpn-connecter.sh lbic toggle"
exec --no-startup-id "rm /tmp/vpn_lbic.tmp"
#+end_src
** Samsung
#+begin_src conf :noweb-ref vpn
bindsym $alt+$mod+4 exec "$SCRIPT_PATH/vpn-connecter.sh samsung toggle"
exec --no-startup-id "rm /tmp/vpn_samsung.tmp"
#+end_src
** Tangle :noexport:
*** i3
#+begin_src conf :noweb yes :tangle _config_i3
<<vpn>>
#+end_src
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<vpn>>
#+end_src
* Startup commands
** Transparency
Set inactive window transparency.
*** i3
#+begin_src conf :noweb-ref i3-transparency
exec_always --no-startup-id picom -b --config ~/.config/picom/picom.conf
#+end_src
*** Sway
#+begin_src conf :noweb-ref sway-transparency
exec /usr/share/sway-contrib/inactive-windows-transparency.py --opacity 0.85
#+end_src
** Touchpad
*** i3
Enable touchpad horizontal scroll
#+begin_src conf :noweb-ref i3-touchpad
exec xinput --set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Two-Finger Scrolling" 1 1
#+end_src
** Caps Lock
*** Sway
Create file to track status of Caps Lock (used by status bar).
#+begin_src conf :noweb-ref sway-capslock
exec echo 0 > /tmp/capslock_status.tmp
#+end_src
** KMonad status
Create file to track KMonad service status (used by status bar).
#+begin_src conf :noweb-ref sway-kmonad
exec --no-startup-id "sudo bash $SCRIPT_PATH/waybar/scripts/kmonad.sh status > /tmp/kmonad-status.tmp"
#+end_src
** Background images
*** i3
Before, wallpapers were set calling =feh= directly in i3wm.
#+begin_src conf :tangle no
exec_always feh \
    --bg-scale ~/.config/wallpaper/london.jpg \
    --bg-scale ~/.config/wallpaper/london.jpg \
    --bg-scale ~/.config/wallpaper/nasa.png
#+end_src

However, this is done through a script (=xrandr-config.sh=) now.
#+begin_src conf :noweb-ref i3-wallpaper
exec_always --no-startup-id "$SCRIPT_PATH/xrandr-wallpaper.sh"
#+end_src
*** Sway
#+begin_src conf :noweb-ref sway-wallpaper
output $laptop    background ~/.config/wallpaper/london.jpg fill
output $primary   background ~/.config/wallpaper/london.jpg fill
output $secondary background ~/.config/wallpaper/london.jpg fill
output $tertiary  background ~/.config/wallpaper/nasa.png fill
#+end_src
** Daemons
*** Common
#+begin_src conf :noweb-ref daemons
exec --no-startup-id /usr/bin/dunst &             # dunst: notification daemon
#exec_always dunstctl set-paused true              # dunst: start with notifications paused
exec --no-startup-id emote                        # emoji picker
exec_always --no-startup-id autotiling            # autotiling
exec --no-startup-id "dex -a -s /home/rafael/.config/autostart"    # XDG Autostart applications
#exec_always --no-startup-id "$SCRIPT_PATH/xremap-keeb-config.sh"   # keyboard setup
exec --no-startup-id /usr/bin/emacs --daemon --with-profile efs &  # launch EFS daemon (default)
exec --no-startup-id /usr/bin/emacs --daemon --with-profile doom & # launch Doom Emacs daemon
#+end_src
*** Config
#+begin_src conf :noweb-ref daemons
exec --no-startup-id "rm /tmp/showmethekey_pid.tmp"               # ensure there is no temp file from previous boot
bindsym $alt+ctrl+e exec emote                                    # emoji picker
bindsym $alt+ctrl+k exec "$SCRIPT_PATH/screencast.sh toggle"      # showmethekey
bindsym $alt+ctrl+d exec dunstctl set-paused toggle               # pause/unpause dunst notifications
bindsym $alt+ctrl+l exec "emacsclient -c -s efs -a emacs"         # emacsclient for EFS
bindsym $alt+ctrl+shift+l exec "emacsclient -c -s doom -a emacs"  # emacsclient for Doom
bindsym $alt+ctrl+w exec "$XDG_CONFIG_HOME/waybar/scripts/mouse-warping.sh toggle"  # enable/disable mouse warping
#+end_src
*** i3
#+begin_src conf :noweb-ref i3-daemons
exec_always --no-startup-id flashfocus
#+end_src
** Panel
*** i3
**** Polybar
#+begin_src conf :noweb-ref i3-polybar
exec_always --no-startup-id ~/.config/polybar/launch.sh
#+end_src
**** i3bar
Start i3bar to display a workspace bar (plus the system information i3status finds out, if available)
#+begin_src conf :noweb-ref i3-i3bar
bar {
    # set i3bar position
    position top
    #-----------------------------
    # display only ws names
    strip_workspace_numbers yes
    #-----------------------------
    #status_command i3status
    status_command i3blocks -c $XDG_CONFIG_HOME/i3/i3blocks.conf
    #-----------------------------
    # set font
    #font pango:DejaVu Sans Mono 4
    font pango:monospace 8
    #-----------------------------
    # system tray area
    tray_output eDP-1   # Y2P
    #tray_output VGA1   # LBiC_L
    #tray_output HDMI3  # LBiC_R
}
#+end_src
*** Sway (Waybar)
#+begin_src conf :noweb-ref sway-waybar
exec_always --no-startup-id ~/.config/waybar/waybar.sh
#+end_src
*** Applets
#+begin_src conf :noweb-ref applets
exec "blueman-applet &"                 # Bluetooth
exec "nm-applet --indicator &"          # NetworkManager
exec "syncthing &"                      # Syncthing
#+end_src
#+begin_src conf :noweb-ref startup-commands
#+end_src
** Tangle :noexport:
*** i3
#+begin_src conf :noweb yes :tangle _config_i3
<<i3-transparency>>
<<i3-touchpad>>
<<i3-wallpaper>>
<<daemons>>
<<i3-daemons>>
#<<i3-i3bar>>
<<i3-polybar>>
<<applets>>
<<startup-commands>>
#+end_src
*** Sway
#+begin_src conf :noweb yes :tangle _config_sway
<<sway-transparency>>
<<sway-capslock>>
<<sway-kmonad>>
<<sway-wallpaper>>
<<daemons>>
<<sway-waybar>>
<<applets>>
<<startup-commands>>
#+end_src
