#+TITLE: Config file for i3/Sway window manager
#+AUTHOR: Rafael Ito
#+PROPERTY: header-args :tangle config_from_org
#+DESCRIPTION: config file for i3/Sway window manager
#+STARTUP: showeverything
#+auto_tangle: t
* Table of contents :toc:
- [[#general-config][General config]]
  - [[#modifiers][Modifiers]]
  - [[#general][General]]
  - [[#font--color][Font & color]]
- [[#sway][Sway]]
  - [[#xdg-desktop-portal-wlr][xdg-desktop-portal-wlr]]
  - [[#inputs][Inputs]]
- [[#outputs][Outputs]]
  - [[#default-scenario][Default Scenario]]
  - [[#msc-presentation][MSc presentation]]
  - [[#hub-viva-bem-1][Hub Viva-Bem 1]]
  - [[#hub-viva-bem-2][Hub Viva-Bem 2]]
  - [[#duplicated-cursor][Duplicated cursor]]
- [[#workspaces-definition][Workspaces definition]]
  - [[#default-output][Default output]]
  - [[#ws-names-icons][WS names (icons)]]
  - [[#ws-names][WS names]]
- [[#i3bang-raw-section-beginning][i3bang: raw section (beginning)]]
- [[#volume-control][Volume control]]
  - [[#i3blocks][i3blocks]]
  - [[#custom-keeb][Custom keeb]]
- [[#window-settings][Window settings]]
  - [[#change-focus][Change focus]]
  - [[#move-window][Move window]]
  - [[#general-1][General]]
- [[#focus][Focus]]
  - [[#windows][Windows]]
  - [[#monitor][Monitor]]
- [[#workspaces-navigation][Workspaces navigation]]
  - [[#switch-to-workspace][Switch to workspace]]
  - [[#move-container-to-ws][Move container to WS]]
  - [[#navigate-on-same-monitor][Navigate on same monitor]]
  - [[#navigate-among-monitors][Navigate among monitors]]
  - [[#move-container-among-monitors][Move container among monitors]]
- [[#restart-i3sway][Restart i3/sway]]
  - [[#reload][Reload]]
  - [[#restart][Restart]]
  - [[#exit][Exit]]
- [[#custom-keybinds][Custom keybinds]]
  - [[#applications][Applications]]
  - [[#terminal][Terminal]]
  - [[#brightness][Brightness]]
  - [[#screenshot][Screenshot]]
  - [[#rofi][Rofi]]
- [[#logitech-mx][Logitech MX]]
  - [[#change-host][Change host]]
  - [[#mx-master-3][MX Master 3]]
- [[#mouse-keybinds][Mouse keybinds]]
  - [[#volume-control-1][Volume control]]
  - [[#mouse-keys][Mouse keys]]
- [[#keyboard-keybinds][Keyboard keybinds]]
  - [[#ctrl--space--return][Ctrl + Space = Return]]
  - [[#mod5-hold-tab][Mod5 (hold Tab)]]
- [[#rotate-screen][Rotate screen]]
  - [[#portrait][Portrait]]
  - [[#landscape][Landscape]]
- [[#i3bang-raw-section-end][i3bang: raw section (end)]]
- [[#modes][Modes]]
  - [[#system][System]]
  - [[#resize][Resize]]
  - [[#number][Number]]
- [[#i3bar][i3bar]]
- [[#applications-default-ws][Applications default WS]]
  - [[#wayland--x11][Wayland / X11]]
  - [[#applications-1][Applications]]
- [[#window-specific][Window-specific]]
  - [[#tkinter][Tkinter]]
- [[#scratchpads][Scratchpads]]
  - [[#python][Python]]
  - [[#terminal-1][Terminal]]
- [[#applets][Applets]]
- [[#startup-commands][Startup commands]]
  - [[#background-images][Background images]]
  - [[#touchpad][Touchpad]]
  - [[#compositor][Compositor]]
  - [[#daemons][Daemons]]
* General config
** Modifiers
| modifier | keys                           |
|----------+--------------------------------|
| Shift    | Shift_L, Shift_R, Henkan       |
| Control  | Control_L, Control_R, Muhenkan |
| Lock     | Caps_Lock                      |
| Mod1     | Alt_L, Alt_R                   |
| Mod2     | Num_Lock                       |
| Mod3     | Super_R                        |
| Mod4     | Super_L                        |
#+begin_src conf
set $alt Mod1
set $mod Mod4
#+end_src
** General
Set window border.
#+begin_src conf
#for_window [class=".*"] border pixel 3
default_border pixel 5
#+end_src

Use Mouse+$mod to drag floating windows.
#+begin_src conf
floating_modifier $mod
#+end_src

Enable previous workspace switching.
#+begin_src conf
workspace_auto_back_and_forth yes
#+end_src

Gaps size
#+begin_src conf
gaps inner 10
#+end_src
** Font & color
Set font for window titles.
#+begin_src conf
font pango:monospace 10
#+end_src

Set ws background, text and htext colors.
#+begin_src conf
set $bg-color    #2f343f
set $text-color  #f3f4f5
set $htext_color #9575cd
#+end_src
* Sway
** xdg-desktop-portal-wlr
#+begin_src conf
include /etc/sway/config.d/*
#+end_src
** Inputs
*** Trackpad
documentation:
https://wayland.freedesktop.org/libinput/doc/latest/index.html
#+begin_src conf
input type:touchpad {
    tap enabled                                   # tap-to-click
    natural_scroll enabled                        # natural scrolling
}
#+end_src
*** Enable NumLock
#+begin_src conf :tangle no
input type:keyboard xkb_numlock enabled
#+end_src
*** Keyboard
**** Model, layout and variant
Load model, layout and variant for all keyboards.
input type:keyboard {
    xkb_model "pc105"
    xkb_layout "us"
    xkb_variant "intl"
}
#+end_src
**** Options
Load generic modifications for all inputs.
#+begin_src conf
input * {
    xkb_options "\
        modifiers:modifiers, \
        fn-keys:fnkeys, \
    "
}
#+end_src
* Outputs
** Default Scenario
This setup is used for the main workstation.
*** Set order
# Outputs:
#
#   +-----------+ +-----------+ +--------+
#   |           | |           | |        |=++
#   | secondary | |  primary  | | terti..| ||
#   |           | |           | |  ..ary | ||
#   +-----------+ +-----------+ |        | ||
#   +---/   \--+  +--/   \---+  |        | ||
#   |----------|  |----------|  +--------+ ||
# --+----------+--+----------+-------------++--
#
**** i3
For X11, it's possible to get the output names directly from xrandr.
#+begin_src conf :tangle no
set $primary   $(xrandr | grep ' connected' | awk '{print $1}' | head -n1 | tail -n1)
set $secondary $(xrandr | grep ' connected' | awk '{print $1}' | head -n2 | tail -n1)
set $tertiary  $(xrandr | grep ' connected' | awk '{print $1}' | head -n3 | tail -n1)
#+end_src
**** Sway
#+begin_src conf
set $primary   HDMI1
set $secondary HDMI3
set $tertiary  VGA1
#+end_src
*** Set resolution
**** i3
#+begin_src conf :tangle no
exec xrandr --output $primary   --mode 1920x1080 --rate 60.00 --brightness 1 --pos 0x0 --primary
exec xrandr --output $secondary --mode 1920x1080 --rate 60.00 --brightness 1 --pos -1920x0
exec xrandr --output $tertiary  --mode 1920x1080 --rate 60.00 --brightness 1 --pos 1920x0 --rotate right
#+end_src
**** Sway
#+begin_src conf :tangle no
output $primary   mode 1920x1080@60hz position     0,0 scale 1
output $secondary mode 1920x1080@60hz position -1920,0 scale 1
output $tertiary  mode 1920x1080@60hz position  1920,0 scale 1 transform 90
#+end_src
** MSc presentation
*** Set order
# Room:
#
#   +----------------------+
#   |                      |
#   |    +-----+ +-----+   |
#   |    | tv1 | | tv2 |   |
#   |    +-----+ +-----+   |
#   |                      |
#   |     +--+     +--+    |
#   |   x |  |  3  |  | x  |
#   |   x |  |     |  | x  |
#   |   x |  |     |  | x  |
#   |   x |  |     |  | x  |
#   |      \  \___/  /     |
#   |    x  \___ 1 _/  x   |
#   |           x          |
#   |                      |
#   |       === 2 ===      |
#   +----------------------+
#
#   x: seats
#
#   1: laptop     native screen
#   2: projector  native HDMI --> EPSON projector
#   3: educart    USB-C HDMI --> Dell monitor
#
#+begin_src conf :tangle no
set $laptop    eDP-1
set $projector HDMI-A-1
set $educart   DP-1
#+end_src
*** Set resolution
#+begin_src conf :tangle no
output $laptop    mode 1920x1080@60hz position 0,0
output $projector mode 1920x1200@60hz position 0,1080 scale 1
output $educart   mode 1920x1080@60hz position 0,-1080 scale 1
#+end_src
** Hub Viva-Bem 1
*** Set order
# Outputs:
#
#   +-------+ +-------+
#   |   2   | |   1   |
#   +-------+ +-------+
#              +-----+
#              |  3  |
#              +-----+
#
#   1: Samsung UR55
#   2: Samsung UR55
#   3: VB laptop
#
#+begin_src conf :tangle no
set $primary   HDMI-A-1
set $secondary DP-1
set $laptop    eDP-1
#+end_src
*** Set resolution
Since scale of output #0 is 1.4, the position offset is:
  - secondary screen [H]: 3840/1.4 = 2742
  - laptop [H]: 3840/1.4 - 1920 = 411
  - laptop [V]: 2160/1.4 = 1542

#+begin_src conf :tangle no
output $primary   mode 3840x2160@60hz position      0,0 scale 1.4
output $secondary mode 3840x2160@60hz position  -2742,0 scale 1.4
output $laptop    mode 1920x1080@60hz position 411,1542 scale 1
#+end_src
** Hub Viva-Bem 2
*** Set order
# Outputs:
#
#           +---------+ +---------+
#           |         | |         |
#  +-----+  |    1    | |    2    |
#  |  3  |  |         | |         |
#  +-----+  +---------+ +---------+
#
#   1: Samsung UR55
#   2: Samsung UR55
#   3: VB laptop
#
#+begin_src conf :tangle no
set $primary   HDMI-A-1
set $secondary DP-1
set $laptop    eDP-1
#+end_src
*** Set resolution
Since scale of output #0 is 1.4, the position offset is:
  - secondary screen [H]: 3840/1.4 = 2742
  - laptop [H]: 3840/1.4 - 1920 = 411
  - laptop [V]: 2160/1.4 = 1542

#+begin_src conf :tangle no
output $primary   mode 3840x2160@60hz position     0,0 scale 1.4
output $secondary mode 3840x2160@60hz position  2742,0 scale 1.4
output $laptop    mode 1920x1080@60hz position -1920,0 scale 1
#+end_src
** Duplicated cursor
https://github.com/swaywm/sway/issues/1666
For HDMI 4K@60Hz:
#+begin_src conf :tangle no
output HDMI-A-1 mode 3840x2160@60hz position 0,0
#+end_src

For USB-C 4K@60Hz:
#+begin_src conf :tangle no
output DP-1 mode 3840x2160@60hz position 0,0
#+end_src
* Workspaces definition
** Default output
*** Primary output
#+begin_src conf
workspace "1:1" output $primary
workspace "2:2" output $primary
workspace "3:3" output $primary
workspace "4:4" output $primary
workspace "5:5" output $primary
workspace "6:6" output $primary
workspace "7:7" output $primary
workspace "8:8" output $primary
workspace "9:9" output $primary
workspace "10:0" output $primary
#+end_src
*** Secondary output
#+begin_src conf
workspace "11:11" output $secondary
workspace "12:12" output $secondary
workspace "13:13" output $secondary
workspace "14:14" output $secondary
workspace "15:15" output $secondary
workspace "16:16" output $secondary
workspace "17:17" output $secondary
workspace "18:18" output $secondary
workspace "19:19" output $secondary
workspace "20:10" output $secondary
#+end_src
*** Tertiary output
#+begin_src conf
workspace "21:21" output $tertiary
workspace "22:22" output $tertiary
workspace "23:23" output $tertiary
workspace "24:24" output $tertiary
workspace "25:25" output $tertiary
workspace "26:26" output $tertiary
workspace "27:27" output $tertiary
workspace "28:28" output $tertiary
workspace "29:29" output $tertiary
workspace "30:20" output $tertiary
#+end_src
** WS names (icons)
*** Primary monitor
#+begin_src conf :tangle no
set $ws1 "1 "
set $ws2 "2 "
set $ws3 "3 "
set $ws4 "4 "
set $ws5 "5 "
set $ws6 "6 "
set $ws7 "7 "
set $ws8 "8 "
set $ws9 "9 "
set $ws0 "10 "
set $ws0 "10 "
#+end_src
*** Secondary monitor
#+begin_src conf :tangle no
set $ws11 "11 "
set $ws12 "12 "
set $ws13 "13 "
set $ws14 "14 "
set $ws15 "15 "
set $ws16 "16 "
set $ws17 "17 "
set $ws18 "18 "
set $ws19 "19 J"
set $ws10 "20 E"
#+end_src
** WS names
*** Primary monitor
#+begin_src conf
set $ws1 "1:1"
set $ws2 "2:2"
set $ws3 "3:3"
set $ws4 "4:4"
set $ws5 "5:5"
set $ws6 "6:6"
set $ws7 "7:7"
set $ws8 "8:8"
set $ws9 "9:9"
set $ws0 "10:0"
#+end_src
*** Secondary monitor
#+begin_src conf
set $ws11 "11:11"
set $ws12 "12:12"
set $ws13 "13:13"
set $ws14 "14:14"
set $ws15 "15:15"
set $ws16 "16:16"
set $ws17 "17:17"
set $ws18 "18:18"
set $ws19 "19:19"
set $ws10 "20:10"
#+end_src
*** Tertiary monitor
#+begin_src conf
set $ws21 "21:21"
set $ws22 "22:22"
set $ws23 "23:23"
set $ws24 "24:24"
set $ws25 "25:25"
set $ws26 "26:26"
set $ws27 "27:27"
set $ws28 "28:28"
set $ws29 "29:29"
set $ws20 "30:20"
#+end_src
* i3bang: raw section (beginning)
Make keybinds reusable in other modes (like inheritance).
Check https://github.com/tckmn/i3bang for more details.
#+begin_src conf
#!nobracket
!@<+default_keybindings
#+end_src
* Volume control
** i3blocks
Use pactl to adjust volume in PulseAudio.
#+begin_src conf :tangle no
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl list sinks | grep 'Sink #' | grep -o '[0-9]*' | xargs -i pactl set-sink-volume {} +5% && pkill -RTMIN+1 i3blocks
bindsym XF86AudioLowerVolume exec --no-startup-id pactl list sinks | grep 'Sink #' | grep -o '[0-9]*' | xargs -i pactl set-sink-volume {} -5% && pkill -RTMIN+1 i3blocks
bindsym XF86AudioMute exec --no-startup-id pactl list sinks | grep 'Sink #' | grep -o '[0-9]*' | xargs -i pactl set-sink-mute {} toggle && pkill -RTMIN+1 i3blocks
bindsym XF86AudioMicMute exec --no-startup-id pactl list sources | grep 'Source #' | grep -o '[0-9]*' | xargs -i pactl set-sink-mute {} toggle && pkill -RTMIN+1 i3blocks
#+end_src
** Custom keeb
*** Volume
Volume up/down coarse.
#+begin_src conf
bindsym XF86AudioRaiseVolume exec --no-startup-id amixer -q sset Master 5%+
bindsym XF86AudioLowerVolume exec --no-startup-id amixer -q sset Master 5%-
#+end_src

Volume up/down fine.
#+begin_src conf
bindsym ctrl+shift+F14 exec --no-startup-id amixer -q sset Master 1%-
bindsym ctrl+shift+F15 exec --no-startup-id amixer -q sset Master 1%+
#+end_src

Mute/unmute audio.
#+begin_src conf
bindsym XF86AudioMute exec --no-startup-id amixer -q sset Master toggle
#+end_src

Set volume to 50%.
#+begin_src conf
bindsym $mod+F15 exec --no-startup-id amixer -q sset Master 50%
#+end_src
*** Microphone
Mic volume up/down coarse.
#+begin_src conf
bindsym ctrl+F14 exec --no-startup-id amixer -q sset Capture 5%-
bindsym ctrl+F15 exec --no-startup-id amixer -q sset Capture 5%+
#+end_src

Mic volume up/down fine.
#+begin_src conf
bindsym shift+F14 exec --no-startup-id amixer -q sset Capture 1%-
bindsym shift+F15 exec --no-startup-id amixer -q sset Capture 1%+
#+end_src

Set mic volume to 50%.
#+begin_src conf
bindsym $mod+F14 exec --no-startup-id amixer -q sset Capture 50%
#+end_src

Mute/unmute mic.
#+begin_src conf
bindsym XF86AudioMicMute exec --no-startup-id amixer -q sset Capture toggle
bindsym shift+$mod+F14 exec --no-startup-id amixer -q sset Capture toggle
#+end_src
* Window settings
** Change focus
*** hjkl
#+begin_src conf :tangle no
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
#+end_src
*** jkl;
#+begin_src conf :tangle no
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right
#+end_src
*** neio
#+begin_src conf
bindsym $mod+n focus left
bindsym $mod+e focus down
bindsym $mod+i focus up
bindsym $mod+o focus right
#+end_src
*** Arrows
#+begin_src conf
bindsym $mod+Left  focus left
bindsym $mod+Down  focus down
bindsym $mod+Up    focus up
bindsym $mod+Right focus right
#+end_src
** Move window
*** hjkl
#+begin_src conf :tangle no
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right
#+end_src
*** jkl;
#+begin_src conf :tangle no
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right
#+end_src
*** neio
#+begin_src conf
bindsym $mod+Shift+n move left
bindsym $mod+Shift+e move down
bindsym $mod+Shift+i move up
bindsym $mod+Shift+o move right
#+end_src
*** Arrows
#+begin_src conf
bindsym $mod+Shift+Left  move left
bindsym $mod+Shift+Down  move down
bindsym $mod+Shift+Up    move up
bindsym $mod+Shift+Right move right
#+end_src
** General
*** Split
Split window in horizontal/vertical orientation
#+begin_src conf
bindsym mod1+h split h
bindsym mod1+v split v
#+end_src
*** Container layout
Change container layout (stacked, tabbed, toggle split).
#+begin_src conf
#bindsym mod1+$mod+s layout stacked
#bindsym mod1+$mod+w layout tabbed
#bindsym mod1+$mod+e layout toggle split
bindsym mod1+$mod+e layout toggle stacked tabbed
#+end_src
*** Fullscreen
Enter fullscreen mode for the focused container.
#+begin_src conf
bindsym mod1+$mod+f fullscreen toggle
#+end_src
*** Tiling/Floating
Toggle between tiling/floating window.
#+begin_src conf
bindsym mod1+$mod+d floating toggle
#+end_src
*** Kill window
Kill focused window, unless it's a scratchpad. Check the [[https://github.com/ito-rafael/dotfiles/blob/master/scripts/sway-kill.sh][sway-kill.sh]] script for more details.
#+begin_src conf
bindsym mod1+$mod+q kill $SCRIPT_PATH/sway-kill.sh
#+end_src
* Focus
** Windows
#+begin_src conf
bindsym $mod+space focus mode_toggle              # change focus between tiling / floating windows
bindsym $mod+a focus parent                       # focus the parent container
#bindsym $mod+d focus child                       # focus the child container
bindsym $mod+z [urgent=latest] focus              # switch to latest urgent window
#+end_src
** Monitor
*** Arrows
#+begin_src conf
bindsym mod1+Left  focus output left
bindsym mod1+Right focus output right
#+end_src
*** hjkl
#+begin_src conf
#bindsym ctrl+$mod+h focus output left
#bindsym ctrl+$mod+l focus output right
#+end_src
* Workspaces navigation
#+begin_src conf
set $SCRIPT_PATH $HOME/.config/scripts
#+end_src
** Switch to workspace
Navigate to workspace and check if there is any window opened there:
  - if there is a window:
    - simply navigate to the workspace
  - if empty:
    - navigate to the workspace
    - restore its layout
    - open windows
*** Primary monitor
#+begin_src conf
bindsym $mod+1 exec "$SCRIPT_PATH/navigate2ws.sh 1"
bindsym $mod+2 exec "$SCRIPT_PATH/navigate2ws.sh 2"
bindsym $mod+3 exec "$SCRIPT_PATH/navigate2ws.sh 3"
bindsym $mod+4 exec "$SCRIPT_PATH/navigate2ws.sh 4"
bindsym $mod+5 exec "$SCRIPT_PATH/navigate2ws.sh 5"
bindsym $mod+6 exec "$SCRIPT_PATH/navigate2ws.sh 6"
bindsym $mod+7 exec "$SCRIPT_PATH/navigate2ws.sh 7"
bindsym $mod+8 exec "$SCRIPT_PATH/navigate2ws.sh 8"
bindsym $mod+9 exec "$SCRIPT_PATH/navigate2ws.sh 9"
bindsym $mod+0 exec "$SCRIPT_PATH/navigate2ws.sh 0"
#+end_src
*** Secondary monitor
#+begin_src conf
bindsym shift+$mod+1 exec "$SCRIPT_PATH/navigate2ws.sh 11"
bindsym shift+$mod+2 exec "$SCRIPT_PATH/navigate2ws.sh 12"
bindsym shift+$mod+3 exec "$SCRIPT_PATH/navigate2ws.sh 13"
bindsym shift+$mod+4 exec "$SCRIPT_PATH/navigate2ws.sh 14"
bindsym shift+$mod+5 exec "$SCRIPT_PATH/navigate2ws.sh 15"
bindsym shift+$mod+6 exec "$SCRIPT_PATH/navigate2ws.sh 16"
bindsym shift+$mod+7 exec "$SCRIPT_PATH/navigate2ws.sh 17"
bindsym shift+$mod+8 exec "$SCRIPT_PATH/navigate2ws.sh 18"
bindsym shift+$mod+9 exec "$SCRIPT_PATH/navigate2ws.sh 19"
bindsym shift+$mod+0 exec "$SCRIPT_PATH/navigate2ws.sh 10"
#+end_src
*** Tertiary monitor
#+begin_src conf
bindsym mod3+1 exec "$SCRIPT_PATH/navigate2ws.sh 21"
bindsym mod3+2 exec "$SCRIPT_PATH/navigate2ws.sh 22"
bindsym mod3+3 exec "$SCRIPT_PATH/navigate2ws.sh 23"
bindsym mod3+4 exec "$SCRIPT_PATH/navigate2ws.sh 24"
bindsym mod3+5 exec "$SCRIPT_PATH/navigate2ws.sh 25"
bindsym mod3+6 exec "$SCRIPT_PATH/navigate2ws.sh 26"
bindsym mod3+7 exec "$SCRIPT_PATH/navigate2ws.sh 27"
bindsym mod3+8 exec "$SCRIPT_PATH/navigate2ws.sh 28"
bindsym mod3+9 exec "$SCRIPT_PATH/navigate2ws.sh 29"
bindsym mod3+0 exec "$SCRIPT_PATH/navigate2ws.sh 20"
#+end_src
** Move container to WS
*** Primary monitor
#+begin_src conf
bindsym ctrl+$mod+1 move container to workspace number $ws1; workspace $ws1
bindsym ctrl+$mod+2 move container to workspace number $ws2; workspace $ws2
bindsym ctrl+$mod+3 move container to workspace number $ws3; workspace $ws3
bindsym ctrl+$mod+4 move container to workspace number $ws4; workspace $ws4
bindsym ctrl+$mod+5 move container to workspace number $ws5; workspace $ws5
bindsym ctrl+$mod+6 move container to workspace number $ws6; workspace $ws6
bindsym ctrl+$mod+7 move container to workspace number $ws7; workspace $ws7
bindsym ctrl+$mod+9 move container to workspace number $ws8; workspace $ws8
bindsym ctrl+$mod+8 move container to workspace number $ws9; workspace $ws9
bindsym ctrl+$mod+0 move container to workspace number $ws0; workspace $ws0
#+end_src
*** Secondary monitor
#+begin_src conf
bindsym shift+ctrl+$mod+1 move container to workspace number $ws11; workspace $ws11
bindsym shift+ctrl+$mod+2 move container to workspace number $ws12; workspace $ws12
bindsym shift+ctrl+$mod+3 move container to workspace number $ws13; workspace $ws13
bindsym shift+ctrl+$mod+4 move container to workspace number $ws14; workspace $ws14
bindsym shift+ctrl+$mod+5 move container to workspace number $ws15; workspace $ws15
bindsym shift+ctrl+$mod+6 move container to workspace number $ws16; workspace $ws16
bindsym shift+ctrl+$mod+7 move container to workspace number $ws17; workspace $ws17
bindsym shift+ctrl+$mod+8 move container to workspace number $ws18; workspace $ws18
bindsym shift+ctrl+$mod+9 move container to workspace number $ws19; workspace $ws19
bindsym shift+ctrl+$mod+0 move container to workspace number $ws10; workspace $ws10
#+end_src
*** Tertiary monitor
#+begin_src conf
bindsym ctrl+mod3+0 move container to workspace number $ws20; workspace $ws20
bindsym ctrl+mod3+1 move container to workspace number $ws21; workspace $ws21
bindsym ctrl+mod3+2 move container to workspace number $ws22; workspace $ws22
bindsym ctrl+mod3+3 move container to workspace number $ws23; workspace $ws23
bindsym ctrl+mod3+4 move container to workspace number $ws24; workspace $ws24
bindsym ctrl+mod3+5 move container to workspace number $ws25; workspace $ws25
bindsym ctrl+mod3+6 move container to workspace number $ws26; workspace $ws26
bindsym ctrl+mod3+7 move container to workspace number $ws27; workspace $ws27
bindsym ctrl+mod3+8 move container to workspace number $ws28; workspace $ws28
bindsym ctrl+mod3+9 move container to workspace number $ws29; workspace $ws29
#+end_src
** Navigate on same monitor
#+begin_src conf
bindsym shift+mod3+Down workspace next_on_output
bindsym shift+mod3+Up  workspace prev_on_output
#+end_src
** Navigate among monitors
#+begin_src conf
bindsym shift+mod3+Left  focus output left
bindsym shift+mod3+Right focus output right
#+end_src
** Move container among monitors
*** Arrows
#+begin_src conf
bindsym $mod+shift+mod3+Left  move container to output left;  focus output left
bindsym $mod+shift+mod3+Right move container to output right; focus output right
#+end_src
*** Numbers
#+begin_src conf
bindsym ctrl+mod1+1 move workspace to output $primary;   focus output $primary
bindsym ctrl+mod1+2 move workspace to output $secondary; focus output $secondary
bindsym ctrl+mod1+3 move workspace to output $tertiary;  focus output $tertiary
#+end_src
* Restart i3/sway
** Reload
#+begin_src conf
#bindsym $mod+Shift+c reload
#bindsym mod1+$mod+c exec ~/.config/i3/i3bang.rb; reload
bindsym mod1+$mod+c exec ~/.config/sway/i3bang.rb; reload
#+end_src
** Restart
Restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
#+begin_src conf
#bindsym mod1+$mod+s exec ~/.config/i3/i3bang.rb; restart
bindsym mod1+$mod+s exec ~/.config/sway/i3bang.rb; restart
#+end_src
** Exit
Exit i3 (logs you out of your X session)
#+begin_src conf
#bindsym mod1+$mod+x exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"
bindsym mod1+$mod+x exec "swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit Sway? This will end your X session.' -B 'Yes, exit Sway' 'swaymsg exit'"
#+end_src
* Custom keybinds
** Applications
#+begin_src conf
bindsym $mod+b exec firefox
#bindsym $mod+c exec chromium
#bindsym $mod+n exec thunar
#bindsym $mod+l exec lollypop
#bindsym $mod+m exec thunderbird
bindsym $mod+g exec kitty ranger
#bindsym $mod+p exec spotify --force-device-scale-factor=2 # shortcut to open Spotify
#+end_src
** Terminal
#+begin_src conf
bindsym $mod+t exec kitty
bindsym mod1+$mod+t exec kitty
#bindsym $mod+t exec i3-sensible-terminal
#bindsym mod1+$mod+t exec i3-sensible-terminal
#bindsym ctrl+$mod+t exec i3-sensible-terminal
#+end_src
** Brightness
#+begin_src conf
#bindsym XF86MonBrightnessUp   exec --no-startup-id xbacklight -inc 5
#bindsym XF86MonBrightnessDown exec --no-startup-id xbacklight -dec 5
bindsym XF86MonBrightnessDown exec brightnessctl set 5%-
bindsym XF86MonBrightnessUp exec brightnessctl set 5%+
#+end_src
** Screenshot
*** i3
#+begin_src conf :tangle no
bindsym Print exec shutter
#+end_src
*** Sway
#+begin_src conf
bindsym Print exec grim
bindsym shift+Print exec 'grim -g "$(slurp)"'
bindsym ctrl+Print exec 'grim -g "$(slurp)" - | swappy -f -'
#+end_src
** Rofi
#+begin_src conf
bindsym $mod+Return       exec rofi -show run    -monitor $(swaymsg -t get_outputs | jq '.[] | select(.focused==true).name')
bindsym $mod+bracketright exec rofi -show window -monitor $(swaymsg -t get_outputs | jq '.[] | select(.focused==true).name')
bindsym $mod+backslash    exec rofi -show ssh    -monitor $(swaymsg -t get_outputs | jq '.[] | select(.focused==true).name')
#+end_src
* Logitech MX
** Change host
Change host for MX Keys and MX Master 3.
#+begin_src conf :tangle no
#bindsym F13 exec /home/rafael/mx_script.sh
bindsym --release F20 exec $SCRIPT_PATH/mx_script.sh
#+end_src
** MX Master 3
*** Copy
"copy" shortcut: "i" button + down gesture.
#+begin_src conf :tangle no
bindsym XF86Copy [class="Xfce4-terminal"] exec "xdotool keydown ctrl keydown shift keydown c keyup ctrl keyup shift keyup c"; exec "sleep 0.1"
#+end_src
*** Paste
"paste" shortcut: "i" button + up gesture.
#+begin_src conf :tangle no
bindsym XF86Paste [class="Xfce4-terminal"] exec "xdotool keydown ctrl keydown shift keydown v keyup ctrl keyup shift keyup v"; exec "sleep 0.1"
#+end_src
#+begin_src conf :tangle no
#+end_src
* Mouse keybinds
** Volume control
*** i3
Use button9 + scroll to control volume.
  --> button9 is mapped as Super_R using the interception tool, which is mapped as mod3 using xmodmap.
#+begin_src conf :tangle no
bindsym mod3+ --whole-window button4 exec "pactl set-sink-volume @DEFAULT_SINK@ +5% && pkill -RTMIN+10 i3blocks"
bindsym mod3+ --whole-window button5 exec "pactl set-sink-volume @DEFAULT_SINK@ -5% && pkill -RTMIN+10 i3blocks"
#+end_src
** Mouse keys
*** Cursor
| key | cursor movement |
|-----+-----------------|
| kp4 | left            |
| kp2 | down            |
| kp8 | up              |
| kp6 | right           |
#+begin_src conf
bindsym kp_4 seat - cursor move -10  0
bindsym kp_2 seat - cursor move  0   10
bindsym kp_8 seat - cursor move  0  -10
bindsym kp_6 seat - cursor move  10  0
#+end_src
*** Buttons
| key | mouse button |
|-----+--------------|
| kp/ | left click   |
| kp* | middle click |
| kb- | right click  |
#+begin_src conf
bindsym kp_divide   seat - cursor press button1
bindsym kp_multiply seat - cursor press button2
bindsym kp_subtract seat - cursor press button3
#+end_src
*** Wheel
| key | wheel movement |
|-----+----------------|
| kp1 | up             |
| kp3 | down           |
| kp7 | right          |
| kp9 | left           |
#+begin_src conf
bindsym kp_1 seat - cursor press button4
bindsym kp_3 seat - cursor press button5
bindsym kp_7 seat - cursor press button6
bindsym kp_9 seat - cursor press button7
#+end_src
* Keyboard keybinds
** Ctrl + Space = Return
#+begin_src conf :tangle no
bindsym --release ctrl+space exec xdotool key Return
#+end_src
** Mod5 (hold Tab)
Navigation with vim keys
#+begin_src conf :tangle no
bindsym --release Mod5+h exec xdotool key Left
bindsym --release Mod5+j exec xdotool key Down
bindsym --release Mod5+k exec xdotool key Up
bindsym --release Mod5+l exec xdotool key Right
#+end_src
* Rotate screen
** Portrait
- rotate screen
- rotate touchscreen
- disable touchpad
- disable touchpad click
#+begin_src conf
bindsym mod1+$mod+Up exec "\
    echo 'rotate screen' &&\
    xrandr --output eDP-1 --rotate left &&\
    echo 'rotate touchscreen' &&\
    xinput set-prop ELAN\ Touchscreen --type=float 'Coordinate Transformation Matrix'  0 -1 1 1 0 0 0 0 1 &&\
    echo 'disable touchpad' &&\
    synclient TouchpadOff=1 &&\
    echo 'disable touchpad click' &&\
    synclient RightButtonAreaLeft=0 &&\
    synclient RightButtonAreaTop=0 \
"
#+end_src
** Landscape
- rotate screen
- rotate touchscreen
- enable touchpad
- enable touchpad click
#+begin_src conf
bindsym mod1+$mod+Down exec "\
    echo 'rotate screen' &&\
    xrandr --output eDP-1 --rotate normal && \
    echo 'rotate touchscreen' &&\
    xinput set-prop ELAN\ Touchscreen --type=float 'Coordinate Transformation Matrix'  0  0 0 0 0 0 0 0 0 &&\
    echo 'enable touchpad' &&\
    synclient TouchpadOff=0 &&\
    echo 'enable touchpad click' &&\
    synclient RightButtonAreaLeft=3472 &&\
    synclient RightButtonAreaTop=4080 \
"
#+end_src
* i3bang: raw section (end)
End raw section: !@<+default_keybindings
#+begin_src conf
>
#+end_src
* Modes
** System
*** Description
source:
https://wiki.archlinux.org/index.php/I3#Shutdown,_reboot,_lock_screen
*** Locker
Adds 1 second delay to prevent possible race conditions with suspend.
**** i3
#+begin_src conf :tangle no
set $locker i3lock --color 000000 && sleep 1
#+end_src
**** Sway
#+begin_src conf
set $locker swaylock --color 000000 && sleep 1
#+end_src
*** Mode
#+begin_src conf
set $mode_system System: (s)hutdown, (r)eboot, (l)ock, (S)uspend, (h)ibernate, (e)xit/logout
#-----------------------------
mode "$mode_system" {
    bindsym l       exec --no-startup-id $locker,                         mode "default"
    bindsym e       exec --no-startup-id i3-msg exit,                     mode "default"
    bindsym Shift+s exec --no-startup-id $locker && systemctl suspend,    mode "default"
    bindsym h       exec --no-startup-id $locker && systemctl hibernate,  mode "default"
    bindsym r       exec --no-startup-id systemctl reboot,                mode "default"
    bindsym s       exec --no-startup-id systemctl poweroff -i,           mode "default"
    #-----------------------------
    # back to normal: Enter or Escape
    bindsym Return    mode "default"
    bindsym Escape    mode "default"
    bindsym $mod+Home mode "default"
    #-----------------------------
    # inherent default keybinds (i3bang)
    !@default_keybindings
}
# obs: the -i argument for systemctl poweroff causes a shutdown even if other users are logged-in (this requires polkit), or when logind (wrongly) assumes so.
#+end_src
*** Keybinding
#+begin_src conf
bindsym $mod+Home mode "$mode_system"
#+end_src
** Resize
*** Description
Resize window (you can also use the mouse for that)
  - These bindings trigger as soon as you enter the resize mode
  - Pressing left will shrink the window’s width.
  - Pressing right will grow the window’s width.
  - Pressing up will shrink the window’s height.
  - Pressing down will grow the window’s height.
*** Mode
#+begin_src conf
mode "resize" {
    #-----------------------------
    # colemak home row
    bindsym n resize shrink width  5 px or 5 ppt
    bindsym e resize shrink height 5 px or 5 ppt
    bindsym i resize grow   height 5 px or 5 ppt
    bindsym o resize grow   width  5 px or 5 ppt
    #-----------------------------
    # same bindings, but for the arrow keys
    bindsym Left  resize shrink width  5 px or 5 ppt
    bindsym Down  resize shrink height 5 px or 5 ppt
    bindsym Up    resize grow   height 5 px or 5 ppt
    bindsym Right resize grow   width  5 px or 5 ppt
    #-----------------------------
    # back to normal: Enter or Escape or $mod+r
    bindsym Return mode "default"
    bindsym Escape mode "default"
    bindsym mod1+$mod+r mode "default"
    #-----------------------------
    # inherent default keybinds (i3bang)
    !@default_keybindings
}
#+end_src
*** Keybinding
#+begin_src conf
bindsym mod1+$mod+r mode "resize"
#+end_src
** Number
*** Description
Edit top right keyboard keys to work as a numpad (for Lenovo Yoga 2 Pro)

+-------+-----------+---------+
| digit | key       | keycode |
+-------+-----------+---------+
|   1   | lum+      |   233   |
|   2   | PrtSc     |   107   |
|   3   | delete    |   119   |
|   4   | '+' & '=' |    21   |
|   5   | backspace |    22   |
|   6   | home      |   110   |
|   7   | '}' & ']' |    35   |
|   8   | '\' & '|' |    51   |
|   9   | End       |   115   |
|   0   | Enter     |    36   |
+-------+---+-------+---------+
| Backspace | PgUp  |   112   |
| Enter     | ' & " |    48   |
+-----------------------------+
*** Mode
#+begin_src conf :tangle no
mode "number" {
    #-----------------------------
    # exit "number" mode and load default Xmodmap file
    #bindsym Escape mode "default"; exec "xmodmap ~/.Xmodmap";
    bindsym $mod+Next mode "default"; exec "xmodmap ~/.Xmodmap";
    #-----------------------------
    # test
    #bindsym Shift+A exec "i3-sensible-terminal";
    #-----------------------------
    # inherent default keybinds (i3bang)
    !@default_keybindings
}
#+end_src
*** Keybinding
Enter "number" mode and load Xmodmap file with number modifications
#+begin_src conf
bindsym $mod+Next mode "number"; exec "xmodmap ~/.Xmodmap_numbers"
#+end_src
* i3bar
Start i3bar to display a workspace bar (plus the system information i3status finds out, if available)
#+begin_src conf :tangle no
bar {
    # set i3bar position
    position top
    #-----------------------------
    # display only ws names
    strip_workspace_numbers yes
    #-----------------------------
    #status_command i3status
    status_command i3blocks -c /home/rafael/.config/i3/i3blocks.conf
    #-----------------------------
    # set font
    #font pango:DejaVu Sans Mono 4
    font pango:monospace 8
    #-----------------------------
    # system tray area
    tray_output eDP-1   # Y2P
    #tray_output VGA1   # LBiC_L
    #tray_output HDMI3  # LBiC_R
}
#+end_src
* Applications default WS
** Window property
*** i3
#+begin_src conf
#set $prop class
#+end_src
*** Sway
#+begin_src conf
set $prop app_id
#+end_src
** Applications
| workspace | application | description          |
|-----------+-------------+----------------------|
|         4 | Thunderbird | Email client         |
|         5 | spreadsheet | LibreOffice          |
|         6 | Lutris      | Gaming               |
|         7 | Nicotine+   | P2P music            |
|         7 | Deluge      | BitTorrent           |
|         8 | Lollypop    | Music player (local) |
|         9 | Spotify     | Music player (web)   |
|        10 | Blueman     | Bluetooth manager    |
|        10 | pavucontrol | Volume control       |
Obs.: both i3/Sway uses "class" for Spotify client.
#+begin_src conf
assign [$prop="thunderbird"] → $ws4
assign [$prop="libreoffice"] → $ws5
assign [$prop="lutris"] → $ws6
assign [$prop="deluge"] → $ws7
assign [$prop="nicotine"] → $ws7
assign [$prop="lollypop"] → $ws8
for_window [class="Spotify"] move --no-auto-back-and-forth to workspace $ws9
assign [$prop="blueman-manager"] → $ws10
assign [$prop="pavucontrol"] → $ws10
#+end_src
* Window-specific
** Tkinter
Floating window for Tkinter (Python GUI)
#+begin_src conf
for_window [class="Tk"] floating enable
for_window [class="Toplevel"] floating enable
#+end_src
* Scratchpads
** Python
#+begin_src conf
exec --no-startup-id kitty --class="dropdown_python" -o font_size=20 python -q
bindsym $mod+y [$prop="^dropdown_python$"] scratchpad show; resize set 1000 600
for_window [$prop="^dropdown_python$"] floating enable
for_window [$prop="^dropdown_python$"] move position center
for_window [$prop="^dropdown_python$"] move scratchpad
for_window [$prop="^dropdown_python$"] border pixel 5
#+end_src
** Terminal
#+begin_src conf
exec --no-startup-id kitty --class="dropdown_terminal"
bindsym $mod+h [$prop="^dropdown_terminal$"] scratchpad show; resize set 1000 600
for_window [$prop="^dropdown_terminal$"] floating enable
for_window [$prop="^dropdown_terminal$"] move position center
for_window [$prop="^dropdown_terminal$"] move scratchpad
for_window [$prop="^dropdown_terminal$"] border pixel 5
#+end_src
* Panel
** i3
i3blocks already configured (or better yet, use polybar).
** Sway
#+begin_src conf
exec_always --no-startup-id ~/.config/waybar/waybar.sh
#+end_src
** Applets
#+begin_src conf
exec "blueman-applet &"                           # Bluetooth
exec "nm-applet --indicator &"                    # NetworkManager
#+end_src
* Startup commands
** Background images
#+begin_src conf
exec_always feh --bg-scale ~/.config/feh/london.jpg
#+end_src
** Touchpad
Enable touchpad horizontal scroll
#+begin_src conf
exec xinput --set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Two-Finger Scrolling" 1 1
#+end_src
** Compositor
*** X.Org
#+begin_src conf
exec_always --no-startup-id picom -b --config ~/.config/picom/picom.conf
#+end_src
*** Sway
#+begin_src conf
exec /usr/share/sway-contrib/inactive-windows-transparency.py --opacity 0.85
#+end_src
** Daemons
#+begin_src conf
exec nohup autokey-gtk                           # launch AutoKey
exec nohup /usr/bin/dunst                        # dunst: notification daemon
exec --no-startup-id autotiling                  # autotiling
exec /usr/bin/emacs --daemon &                   # Emacs daemon
#+end_src
