- name: software | window-manager | sway
  package:
    name:
      - gnu-free-fonts
      - seatd
      - sway

- name: users | rafael | add to seat group
  user:
    name: rafael
    groups: seat
    append: yes

- name: service | seatd | start
  systemd:
    name: seatd
    enabled: yes
    state: started
