- name: system | fcron | install package
  package:
    name: "{{ cron_package }}"
    state: latest

- name: system | fcron | start daemon
  systemd:
    name: fcron
    state: started
    enabled: yes
  when: ansible_distribution == "Archlinux"

- name: system | fcron | crontab symlink
  file:
    src: /usr/bin/fcrontab
    path: /usr/bin/crontab
    state: link
