[general]

temp-day=6500
temp-night=3500

fade=1

;elevation-high=3
;elevation-low=-6

;dawn-time=6:00-7:45
;dusk-time=18:35-20:15

;brightness=0.9
;brightness-day=0.7
;brightness-night=0.4

gamma=0.8
;gamma=0.8:0.7:0.8
;gamma-day=0.8:0.7:0.8
;gamma-night=0.6

location-provider=manual

adjustment-method=wayland

[manual]
lat=-23.5
lon=-46.6

[wayland]
output=eDP-*
