#+TITLE: Thunderbird Policies
#+AUTHOR: Rafael Ito
#+PROPERTY: header-args :padline no :tangle policies.json
#+DESCRIPTION: config file to automate the configuration of Thunderbird
#+STARTUP: showeverything
#+auto_tangle: t

* Table of contents :toc_3:
- [[#init][Init]]
  - [[#policies-start][Policies Start]]
- [[#extensions][Extensions]]
  - [[#template][Template]]
  - [[#external-editor-revived][+External Editor Revived+]]
  - [[#tbkeys-lite][+tbkeys-lite+]]
  - [[#tbhints][tbhints]]
  - [[#tbkeys][tbkeys]]
  - [[#ublock-origin][uBlock Origin]]
- [[#end][End]]
  - [[#preferences-and-closing][Preferences and closing]]

* Init
** Policies Start
#+begin_src js
{
  "policies": {
    "DisableAppUpdate": true,
    "DisableTelemetry": true,
#+end_src
* Extensions
#+begin_src js
    "ExtensionSettings": {
#+end_src
** Template
#+name: install
#+begin_src js :var comma=1 extension_id="addon" install_url="url" :results output :tangle no
console.log(`      "${extension_id}": {`);
console.log(`        "installation_mode": "force_installed",`);
console.log(`        "install_url": "${install_url}"`);
if (comma == true){
    console.log(`      },`);
} else {
    console.log(`      }`);
}
#+end_src
** +External Editor Revived+
- link: https://addons.thunderbird.net/en-US/thunderbird/addon/external-editor-revived
- description: Edit emails in an external editor like Neovim or Emacs.
#+begin_src js :noweb yes :tangle no
<<install(extension_id="exteditorR@vletnx.com", install_url="https://addons.thunderbird.net/thunderbird/downloads/latest/external-editor-revived/latest.xpi", comma=1)>>
#+end_src
** +tbkeys-lite+
- link: https://addons.thunderbird.net/en-US/thunderbird/addon/tbkeys-lite
- description: Custom keybindings for Thunderbird (version with no javascript execution).
#+begin_src js :noweb yes :tangle no
<<install(extension_id="tbkeys-lite@addons.thunderbird.net", install_url="https://addons.thunderbird.net/thunderbird/downloads/latest/tbkeys-lite/latest.xpi", comma=1)>>
#+end_src
** tbhints
- link: https://addons.thunderbird.net/en-US/thunderbird/addon/tbhints
- description: Link hints for messages.
#+begin_src js :noweb yes
<<install(extension_id="tbhints@addons.thunderbird.net", install_url="https://addons.thunderbird.net/thunderbird/downloads/latest/tbhints/latest.xpi", comma=1)>>
#+end_src
** tbkeys
- link: https://github.com/wshanks/tbkeys
- description: Custom keybindings for Thunderbird (full version).
#+begin_src js :noweb yes
<<install(extension_id="tbkeys@addons.thunderbird.net", install_url="https://github.com/wshanks/tbkeys/releases/latest/download/tbkeys.xpi", comma=1)>>
#+end_src
** uBlock Origin
- link: https://addons.thunderbird.net/en-US/thunderbird/addon/ublock-origin/
- description: Finally, an efficient blocker. Easy on CPU and memory.
#+begin_src js :noweb yes
<<install(extension_id="uBlock0@raymondhill.net", install_url="https://addons.thunderbird.net/thunderbird/downloads/latest/ublock-origin/latest.xpi", comma=0)>>
#+end_src
** EoS :noexport:
Don't forget to remove the trailing comma on the previous block of JSON code (last extension).
#+begin_src js
    },
#+end_src
* End
** Preferences and closing
#+begin_src js
    "Preferences": {
      "mail.spam.manualMark": true
    }
  }
}
#+end_src
