#+TITLE: OpenTofu config file for Semaphore-UI/Ansible
#+AUTHOR: Rafael Ito
#+PROPERTY: header-args :tangle semaphore.tf
#+DESCRIPTION: OpenTofu config file for Semaphore-UI/Ansible
#+STARTUP: showeverything
#+auto_tangle: t

* Table of Contents :toc_3:
- [[#ansible-provision][ansible-provision]]
  - [[#terraform][Terraform]]
  - [[#provider][Provider]]
  - [[#project][Project]]
  - [[#key-store][Key Store]]
  - [[#repositories][Repositories]]
  - [[#variable-groups-environment][Variable Groups (Environment)]]
  - [[#inventory][Inventory]]
  - [[#task-templates][Task Templates]]
    - [[#task][Task]]

* ansible-provision
** Terraform
#+begin_src conf
terraform {
  required_providers {
    semaphoreui = {
      source  = "registry.terraform.io/semaphoreui/semaphore"
      version = "~> 0.2.2"
    }
  }
}
#+end_src
** Provider
Provider setup: how OpenTofu authenticates to Semaphore.
{url,token} are being passed via env vars SEMAPHOREUI_API_{BASE_URL,TOKEN}.
#+begin_src conf
provider "semaphoreui" {
  #url   = "http://localhost:3000"
  #token = "your_personal_access_token_here"
}
#+end_src
** Project 
#+begin_src conf
resource "semaphoreui_project" "ansible-provision" {
  name = "ansible-provision"
}
#+end_src
** Key Store
#+begin_src conf
resource "semaphoreui_project_key" "none" {
  project_id = semaphoreui_project.ansible-provision.id
  name       = "None"
  none       = {}
}
#+end_src
** Repositories :noexport_1:
*** GitHub
Used for deploys.
#+begin_src conf
resource "semaphoreui_project_repository" "github_repo" {
  project_id = semaphoreui_project.ansible-provision.id
  name       = "ansible-provision"
  url        = "https://github.com/ito-rafael/ansible-provision"
  branch     = "main"
  ssh_key_id = semaphoreui_project_key.none.id
}
#+end_src
*** Local (test)
Used for local tests.
#+begin_src conf
resource "semaphoreui_project_repository" "local_repo" {
  project_id = semaphoreui_project.ansible-provision.id
  name       = "local (test)"
  url        = "file:///home/rafael/git/ansible-provision"
  branch     = "main"
  ssh_key_id = semaphoreui_project_key.none.id
}
#+end_src
** Variable Groups (Environment) :noexport_1:
*** Linear strategy
#+begin_src conf
resource "semaphoreui_project_environment" "linear_strategy" {
  project_id  = semaphoreui_project.ansible-provision.id
  name        = "Linear Strategy"
  environment = {
    "ANSIBLE_STRATEGY" = "linear"
  }
}
#+end_src
*** Empty
Mitogen enabled.
#+begin_src conf
resource "semaphoreui_project_environment" "empty_environment" {
  project_id  = semaphoreui_project.ansible-provision.id
  name        = "Empty"
  environment = {}
}
#+end_src
** Inventory
#+begin_src conf
resource "semaphoreui_project_inventory" "file_inventory" {
  project_id    = semaphoreui_project.ansible-provision.id
  name          = "ansible-provision"
  ssh_key_id    = semaphoreui_project_key.none.id
  file = {
    repository_id = semaphoreui_project_repository.github_repo.id
    path          = "inventory/hosts.yml"
  }
}
#+end_src
** Task Templates
*** Task
**** GitHub
#+begin_src conf
resource "semaphoreui_project_template" "github_template" {
  project_id     = semaphoreui_project.ansible-provision.id
  name           = "ansible-provision"
  playbook       = "local.yml"
  repository_id  = semaphoreui_project_repository.github_repo.id
  inventory_id   = semaphoreui_project_inventory.file_inventory.id
  #environment_id = semaphoreui_project_environment.linear_strategy.id
  environment_id = semaphoreui_project_environment.empty_environment.id

  # Ansible Options & Prompts
  # The provider allows you to set the default CLI arguments or limit strings directly.
  # The specific UI prompt toggles (Tags: enabled, etc.) are currently handled by allowing overrides.
  allow_override_args_in_task = true
}
#+end_src
**** Local (test)
#+begin_src conf
resource "semaphoreui_project_template" "local_template" {
  project_id     = semaphoreui_project.ansible-provision.id
  name           = "local (test)"
  playbook       = "local.yml"
  repository_id  = semaphoreui_project_repository.local_repo.id
  inventory_id   = semaphoreui_project_inventory.file_inventory.id
  #environment_id = semaphoreui_project_environment.linear_strategy.id
  environment_id = semaphoreui_project_environment.empty_environment.id

  allow_override_args_in_task = true
}
#+end_src
