#+TITLE: Surfingkeys
#+AUTHOR: Rafael Ito
#+PROPERTY: header-args :tangle surfingkeys.js
#+DESCRIPTION: config file for the Surfingkeys browser extension using the Colemak-DH keyboard layout
#+STARTUP: showeverything
#+auto_tangle: t

* Table of Contents :toc:
- [[#information][Information]]
  - [[#how-to-load-config-file][How to load config file]]
  - [[#inspiration][Inspiration]]
- [[#general][General]]
  - [[#characters-for-links][Characters for links]]
  - [[#normal-mode][Normal mode]]
  - [[#exceptions][Exceptions]]

* Information
** How to load config file
1. Copy the config file into your $XDG_CONFIG_HOME ($HOME/.config).
#+begin_src sh :tangle no
mkdir -p $XDG_CONFIG_HOME/surfingkeys
cp ./surfingkeys.js $XDG_CONFIG_HOME/surfingkeys.js
#+end_src

1. Open the SurfingKeys settings page: =chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/options.html=

2. Change the =Load settings from= field and insert the *full* path for your config file: =file:///home/<USERNAME>/.config/surfingkeys/surfingkeys.js=
** Inspiration
https://github.com/kalbasit/soxincfg/blob/57847175e30dd9d0cc3a79816e44c87b02e16fc0/modules/programs/chromium/surfingkeys.js#L4
* General
** Characters for links
#+begin_src js
api.Hints.setCharacters('neiohtsrad');
#+end_src
** Normal mode
*** Backup
Save the original bindings into aliases to avoids dependency/order issues.
#+begin_src js
api.vmap("_h",  "h");
api.vmap("_j",  "j");
api.vmap("_k",  "k");
api.vmap("_l",  "l");
#+end_src
*** Unmap
Unmap the orinal bindings that were backed up.
#+begin_src js
api.vunmap("h");
api.vunmap("j");
api.vunmap("k");
api.vunmap("l");
#+end_src
*** Remap
#+begin_src js
api.vmap("n",  "_h");
api.vmap("e",  "_j");
api.vmap("i",  "_k");
api.vmap("o",  "_l");
#+end_src
**** History navigation
#+begin_src js
api.map("N", "_S");
api.map("O", "_D");
api.vunmap("_h");
api.vunmap("_j");
api.vunmap("_k");
api.vunmap("_l");
#+end_src
**** Tab navigation
#+begin_src js
api.map("E", "_R");
api.map("I", "_E");
#+end_src
**** Open links
#+begin_src js
api.map("F", "_af");
#+end_src
*** Delete
Remove the old bindings.
#+begin_src js
#+end_src
** Exceptions
#+begin_src js
api.unmapAllExcept([], /localhost/);
#+end_src
