#+TITLE: Surfingkeys
#+AUTHOR: Rafael Ito
#+PROPERTY: header-args :tangle surfingkeys.js
#+DESCRIPTION: config file for the Surfingkeys browser extension using the Colemak-DH keyboard layout
#+STARTUP: showeverything
#+auto_tangle: t

* Table of Contents :toc:
- [[#information][Information]]
  - [[#how-to-load-config-file][How to load config file]]
  - [[#inspiration][Inspiration]]
- [[#config-file][Config file]]
  - [[#characters-for-links][Characters for links]]
  - [[#normal-mode][Normal mode]]

* Information
** How to load config file
1. Copy the config file into your $XDG_CONFIG_HOME ($HOME/.config).
#+begin_src sh :tangle no
mkdir -p $XDG_CONFIG_HOME/surfingkeys
cp ./surfingkeys.js $XDG_CONFIG_HOME/surfingkeys.js
#+end_src

1. Open the SurfingKeys settings page: =chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/options.html=

2. Change the =Load settings from= field and insert the *full* path for your config file: =file:///home/<USERNAME>/.config/surfingkeys/surfingkeys.js=
** Inspiration
https://github.com/kalbasit/soxincfg/blob/57847175e30dd9d0cc3a79816e44c87b02e16fc0/modules/programs/chromium/surfingkeys.js#L4
* Config file
** Characters for links
#+begin_src js
api.Hints.setCharacters('neiohtsrad');
#+end_src
** Normal mode
*** Backup
Save the original bindings into aliases to avoids dependency/order issues.
#+begin_src js
api.map("_h",  "h");
api.map("_j",  "j");
api.map("_k",  "k");
api.map("_l",  "l");
api.map("_S",  "S");
api.map("_D",  "D");
api.map("_E",  "E");
api.map("_R",  "R");
api.map("_I",  "I");
api.map("_af", "af");
#+end_src
*** Unmap
Unmap the orinal bindings that were backed up.
#+begin_src js
api.vmap("n", "h");
api.vmap("e", "j");
api.vmap("i", "k");
api.vmap("o", "l");
api.unmap("h");
api.unmap("j");
api.unmap("k");
api.unmap("l");
api.unmap("S");
api.unmap("D");
api.unmap("E");
api.unmap("R");
api.unmap("I");
api.unmap("af");
#+end_src
*** Remap
**** Scroll
#+begin_src js
api.map("n", "_h");
api.map("e", "_j");
api.map("i", "_k");
api.map("o", "_l");
#+end_src
**** History navigation
#+begin_src js
api.map("N", "_S");
api.map("O", "_D");
#+end_src
**** Tab navigation
#+begin_src js
api.map("E", "_R");
api.map("I", "_E");
#+end_src
**** Open links
#+begin_src js
api.map("F", "_af");
#+end_src
*** Delete
Remove the old bindings.
#+begin_src js
api.unmap("_h");
api.unmap("_j");
api.unmap("_k");
api.unmap("_l");
api.unmap("_S");
api.unmap("_D");
api.unmap("_E");
api.unmap("_R");
api.unmap("_I");
#+end_src
#+end_src
