# Outputs:
#
#   +-----------+ +-----------+ +--------+
#   |           | |           | |        |=++
#   | secondary | |  primary  | | terti..| ||
#   |           | |           | |  ..ary | ||
#   +-----------+ +-----------+ |        | ||
#   +---/   \--+  +--/   \---+  |        | ||
#   |----------|  |----------|  +--------+ ||
# --+----------+--+----------+-------------++--
#
#
profile {
    output "HDMI-A-1" mode 1920x1080@60hz position 1920,0               # primary
    output "DP-1"     mode 1920x1080@60hz position    0,0               # secondary
    output "DVI-I-1"  mode 1920x1080@60hz position 3840,0 transform 90  # tertiary
}
