---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: restart fcron daemon
    systemd:
      name: fcron
      state: restarted
      enabled: yes

- hosts: all
  tags: base
  become: true
  roles:
    - base

- hosts: workstation
  tags: workstation
  become: true
  roles:
    - workstation
...
