---
- hosts: localhost
  connection: local
  become: true

  tasks:

  - name: install packages
    package:
      name:
        - fcron

  - name: create ansible user
    user:
      name: ansible
      system: yes

  - name: give ansible user sudo permission
    copy:
      src: files/sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440

  - name: create symlink to crontab
    file:
      src: /usr/bin/fcrontab
      path: /usr/bin/crontab
      state: link

  - name: add ansbile user to fcron.allow
    lineinfile:
      path: /etc/fcron/fcron.allow
      line: ansible
