---
- hosts: localhost
  connection: local
  become: true

  tasks:

  - name: install packages
    package:
      name:
        - fcron

  - name: create ansible user
    user:
      name: ansible
      system: yes

