# music directory
music_directory "~/Music"

# set MPD files
playlist_directory "~/.local/share/mpd/playlists"
db_file "~/.local/share/mpd/database"
log_file "~/.local/share/mpd/log"
pid_file "~/.local/share/mpd/pid"
state_file "~/.local/share/mpd/state"

# use PipeWire for audio
audio_output {
    type "pipewire"
    name "PipeWire Sound Server"
}