# environment variables
export GTK_THEME=Adwaita:dark

# PATH
export PATH=$PATH:~/.cargo/bin                              # Rust
export PATH=$PATH:~/.emacs.d/bin                            # Emacs
export PATH=$PATH:/usr/local/texlive/2025/bin/x86_64-linux  # TeX Live
#-----------------------------
# Java
# font rendering
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'

# XDG
export XDG_CONFIG_HOME=$HOME/.config

# directories
export SCRIPTS=$XDG_CONFIG_HOME/scripts

# Zsh
export ZDOTDIR=$HOME/.config/zsh

# TeX Live
export TEXMFDIST='/usr/local/texlive/2025/texmf-dist'
export TEXMFHOME=$XDG_DATA_HOME/texmf
export TEXMFVAR=$XDG_CACHE_HOME/texlive/texmf-var
export TEXMFCONFIG=$XDG_CONFIG_HOME/texlive/texmf-config

# scrcpy
export SDL_VIDEODRIVER=wayland

# mapping for SNES gamepad
export SDL_GAMECONTROLLERCONFIG="0300cb231f08000001e4000010010000,SFC Controller,a:b2,b:b1,back:b8,dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1,leftshoulder:b4,rightshoulder:b5,start:b9,x:b3,y:b0,platform:Linux,"
