# -*- mode: shell-script -*-

## run sway from tty
#if [ -z $DISPLAY ] && [ "$(tty)" = "/dev/tty1" ]; then
#  exec sway --unsupported-gpu
#fi

export ZSH=$HOME/.config/oh-my-zsh

plugins=()
plugins+=(git)
plugins+=(sudo)
plugins+=(web-search)
plugins+=(dirhistory)
plugins+=(history-substring-search)
plugins+=(colored-man-pages)
plugins+=(globalias)
#plugins+=(vi-mode)
#plugins+=(zsh-vi-mode)

GLOBALIAS_FILTER_VALUES=()
GLOBALIAS_FILTER_VALUES+=(ls)
GLOBALIAS_FILTER_VALUES+=(cp)
GLOBALIAS_FILTER_VALUES+=(cpy)
GLOBALIAS_FILTER_VALUES+=(mv)
GLOBALIAS_FILTER_VALUES+=(mvy)
GLOBALIAS_FILTER_VALUES+=(rm)
GLOBALIAS_FILTER_VALUES+=(rmy)
GLOBALIAS_FILTER_VALUES+=(ip)
GLOBALIAS_FILTER_VALUES+=(df)
GLOBALIAS_FILTER_VALUES+=(cat)
GLOBALIAS_FILTER_VALUES+=(diff)
GLOBALIAS_FILTER_VALUES+=(grep)
GLOBALIAS_FILTER_VALUES+=(paru)
GLOBALIAS_FILTER_VALUES+=(sudo)
GLOBALIAS_FILTER_VALUES+=(tlmgr)
GLOBALIAS_FILTER_VALUES+=(catp)
GLOBALIAS_FILTER_VALUES+=(ssh)

powerline-daemon -q
source /usr/share/powerline/bindings/zsh/powerline.zsh

source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source /usr/share/zsh/plugins/zsh-vi-mode/zsh-vi-mode.zsh

#source /usr/share/zsh/plugins/zsh-system-clipboard/zsh-system-clipboard.zsh

#ls_after_cd() ls
ls_after_cd() {
    emulate -L zsh
    exa -alg --color=always --group-directories-first
}
chpwd_functions+=( ls_after_cd )

# detect TRAMP or other "dumb" terminals
# this block of text must be placed before Oh-My-Zsh is sourced
if [[ "$TERM" == "dumb" ]]; then
  unsetopt zle              # disable the Zsh Line Editor (interactive features)
  unsetopt prompt_cr        # disable carriage return printing
  unsetopt prompt_subst     # disable prompt substitution
  unfunction precmd         # disable precmd functions (often used by themes)
  unfunction preexec        # disable preexec functions
  PS1='$ '                  # set a simple, standard prompt
  return                    # stop processing the rest of the file
fi

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# general
alias v=vim                                     # Vim
alias v0=nvim -u NONE -U NONE -N -i NONE        # Vim without configuration
alias m=man                                     # man
alias j=joplin                                  # joplin
alias k=kill                                    # kill
alias h=history                                 # history
alias hg='history | grep'                       # history + grep
alias r=ranger                                  # ranger
alias -g g='| grep'                             # grep
#alias |v='| vim -'                             # pipe to vim
alias df='df -h'                                # df
alias cpr='cp -R'                               # cp recursive
alias psa='ps aux'                              # ps aux
alias psag='ps aux | grep'                      # ps aux | grep
alias {chx,cx}='chmod +x'                       # chmod
alias cux='chmod u+x'                           # chmod (owner-only)
alias sdm='sudo dmesg --ctime'                  # dmesg
alias sdf='sudo dmesg --follow --ctime'         # dmesg follow
alias ns='nvidia-smi'                           # NVIDIA
alias dd='dd bs=4M status=progress oflag=sync'  # dd
alias mi='mediainfo'                            # mediainfo
#alias qq='systemctl start --user ydotool && systemctl start --user xremap'
#alias ww='systemctl stop --user ydotool && systemctl stop --user xremap'
alias {tarc,tc}='tar -czvf'
alias {tarx,tx}='tar -xvzf'
alias wdf='watch -n1 df -h'
alias fl='faillock --user $USER --reset'
alias kb='pkill brave && brave &'
alias km='$XDG_CONFIG_HOME/waybar/scripts/kmonad.sh'
alias ssh='kitten ssh --kitten=color_scheme=themes/ssh.conf'
alias cmd='command'
alias rmw='rm -rf ~/.cache/wasistlos/'          # clean WasIstLos (WhatsApp) cache
function cv() { cat $1 | vim - }

alias j='journalctl -u'                    # journalctl
alias jf='journalctl --follow -u'          # journalctl follow
alias ju='journalctl --user -u'            # journalctl user
alias jfu='journalctl --user --follow -u'  # journalctl user follow

alias wt='watch -n 1'                   # watch
alias wtc='watch -n 1 "cat '            # watch "cat"
alias wtl='watch -n 1 "ls '             # watch "ls"
alias wtp='watch -n 1 "ps aux | grep '  # watch "ps aux"

alias p1='ping 192.168.0.'                         # ping local IP
alias pl='ping 192.168.0.'                         # ping local IP
alias p8='ping 8.8.8.8'                            # ping test (no DNS)
alias pg='ping google.com'                         # ping test with DNS
alias nsn='$XDG_CONFIG_HOME/scripts/nmap.sh'       # nmap -sn (automatic interface: eth > wlp)
alias nsnw='$XDG_CONFIG_HOME/scripts/nmap.sh wlp'  # nmap -sn on wireless interface
alias nsne='$XDG_CONFIG_HOME/scripts/nmap.sh eth'  # nmap -sn on Ethernet interface

#alias ls='ls --color=auto'

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

alias ip='ip -color=auto'
alias ipa='ip -br -c a s'

alias incognito=' unset HISTFILE &&'

alias wlprop='$XDG_CONFIG_HOME/scripts/wlprop.sh'

alias tlmgr='$TEXMFDIST/scripts/texlive/tlmgr.pl --usermode'

alias firefox=firefox-developer-edition

alias contiker="docker run --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 --mount type=bind,source=$CNG_PATH,destination=/home/user/contiki-ng -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/bus/usb:/dev/bus/usb -ti contiker/contiki-ng"

alias ms='rsync -avzhP rafael@143.106.45.169:/home/rafael/git/masters/ /home/rafael/git/masters'

alias rmm='find $HOME/Downloads -type f -name "planck_ez_glow_inkl-p-*.bin" -or -name "zsa_moonlander_inkl-m-*.bin" | xargs rm -f --'
alias wcm='wally-cli "$(command ls -t zsa_moonlander_inkl-m-*.bin | head -1)"'
alias wcp='wally-cli "$(command ls -t planck_ez_glow_inkl-p-*.bin | head -1)"'

alias {paru,yay}='paru --aur'                # paru/yay
alias {sps,spi}='sudo pacman -S'             # pacman install
alias spu='sudo pacman -Syu'                 # pacman update/upgrade
alias spr='sudo pacman -Rns'                 # pacman uninstall
alias spc='paccache -r -k 1'                 # pacman clean
alias pss='pacman -Ss'                       # pacman search packages
alias pqi='pacman -Qi'                       # pacman query installed
alias pqs='pacman -Qs'                       # pacman list installed
alias pqm='pacman -Qm'                       # pacman list foreign
alias prs='paru -S'                          # paru install
alias pru='paru -Syu'                        # paru update/upgrade
alias prm='paru -Rns'                        # paru uninstall
alias prc='paru -Scc'                        # paru clean
alias prd='paru -Sccd'                       # paru clean & delete
alias pqc='sudo pacman -Rs $(pacman -Qtdq)'  # delete unused packages

alias {p,py}=python                             # interpreter
alias piu='pip install -U'                      # pip install
alias pir='pip install -U -r requirements.txt'  # requirements
alias penv='python -m venv'                     # venv
alias da='deactivate'                           # deactivate venv

function ve() {
    cd $HOME/venvs
    python -m venv $1
    cd $1
    source bin/activate
    pip install -U powerline-status
}

function va() {
    cd $HOME/venvs/$1
    source bin/activate
}

alias ma='mamba activate'
alias md='mamba deactivate'
alias ml='mamba env list'
alias mr='mamba env remove -n'

alias ed='emacs --daemon --with-profile efs &'               # start daemon
alias ec='emacsclient -c -s efs -a emacs'                    # launch emacsclient
alias em='emacs --init-dir ~/.config/emacs-efs'              # launch emacs
alias ei='vim $XDG_CONFIG_HOME/emacs-efs/init.el'            # open config file
alias ke='pkill -f "emacs.* --daemon --with-profile efs" && emacs --daemon --with-profile efs &'  # restart daemon
alias rme='rm -f ~/.config/emacs-efs/desktop/emacs.desktop'  # delete emacs.desktop file

alias edd='emacs --daemon --with-profile doom &'             # start daemon
alias ecd='emacsclient -c -s doom -a emacs'                  # launch emacsclient
alias emd='emacs --init-dir ~/.config/emacs-doom'            # launch emacs
alias edc='vim $XDG_CONFIG_HOME/emacs-doom/config.el'        # open config file
alias ked='pkill -f "emacs.* --daemon --with-profile doom" && emacs --daemon --with-profile doom &'  # restart daemon
alias edp='vim $XDG_CONFIG_HOME/emacs-doom/packages.el'
alias dod='doom doctor'
alias dos='doom sync'
alias rme='rm -f ~/.config/emacs-efs/desktop/emacs.desktop'

alias sta='sudo systemctl start'
alias sto='sudo systemctl stop'
alias sen='sudo systemctl enable --now'
alias ssr='sudo systemctl restart'
alias sse='sudo systemctl enable'
alias ssd='sudo systemctl disable'
alias sss='systemctl status'
alias sdr='sudo systemctl daemon-reload'

alias stau='systemctl start --user'
alias stou='systemctl stop --user'
alias ssru='systemctl restart --user'
alias senu='systemctl enable --now --user'
alias sseu='systemctl enable --user'
alias ssdu='systemctl disable --user'
alias sssu='systemctl status --user'
alias sdru='systemctl daemon-reload --user'

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cdd='cd $HOME/Downloads'
alias cdg='cd $HOME/git'
alias cdh='cd $HOME/git/homelab'
alias cdk='cd $HOME/git/keebab'
alias cdks='cd $HOME/git/keebab/scripts'
alias cda='cd $HOME/git/ansible-provision'
alias cdm='cd $HOME/git/machine-learning'
alias cdy='cd $HOME/0_Y2P_SSH_BAK/home/rafael'
alias cdu='cd $HOME/0_Y2P_SSH_BAK/home/rafael/RAFAEL/UNICAMP'
alias cdt='cd $HOME/git/masters/Thesis'
alias cdenv='cd $HOME/venvs'
#alias cdu='cd $HOME/RAFAEL/UNICAMP'

alias cdp='cd $HOME/git/dotfiles'
alias cdpe='cd $HOME/git/dotfiles/emacs'
alias cdpk='cd $HOME/git/dotfiles/kitty'
alias cdpi='cd $HOME/git/dotfiles/i3-sway'
alias cdps='cd $HOME/git/dotfiles/scripts'
alias cdpv='cd $HOME/git/dotfiles/nvim'
alias cdpx='cd $HOME/git/dotfiles/xremap'
alias cdpz='cd $HOME/git/dotfiles/zsh'
alias cdpw='cd $HOME/git/dotfiles/waybar'
alias cdpws='cd $HOME/git/dotfiles/waybar/scripts'

alias cdc='cd $XDG_CONFIG_HOME'
alias cde='cd $XDG_CONFIG_HOME/emacs-efs'
alias cds='cd $XDG_CONFIG_HOME/scripts'
alias cdx='cd $XDG_CONFIG_HOME/xremap'
alias cdi='cd $XDG_CONFIG_HOME/i3'
alias cdi='cd $XDG_CONFIG_HOME/sway'
alias cdv='cd $XDG_CONFIG_HOME/nvim'
alias cdw='cd $XDG_CONFIG_HOME/waybar'
alias cdws='cd $XDG_CONFIG_HOME/waybar/scripts'
alias cdkt='cd $XDG_CONFIG_HOME/kitty'
alias cdz='cd $XDG_CONFIG_HOME/zsh'

alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

alias mvy='command mv'
alias rmy='command rm'
alias cpy='command cp'
alias cpry='command cp -R'

alias rmf='rm -rf'

function de() { docker exec -it $(docker ps | grep $1 | awk '{print $1}') ${2:-bash} }
function dl() { docker logs $(docker ps | grep $1 | awk '{print $1}') }
function dc() { docker-compose $1 }
function dri() { docker run -it --rm $1 ${2:-/bin/bash} }

alias dr='docker run'
alias di='docker images'
alias db='docker build -t'
alias dt='docker tag'
alias drm='docker image rm --force'
alias dso='docker stop'
alias dps='docker ps'
alias dsp='docker system prune'
alias dspa='docker system prune -a'

alias dcu='docker-compose -p $(pwd | rev | cut -d '/' -f 2 | rev) up -d'
alias dcd='docker-compose -p $(pwd | rev | cut -d '/' -f 2 | rev) down'
alias dcr='docker-compose -p $(pwd | rev | cut -d '/' -f 2 | rev) restart'
alias dcl='docker-compose -p $(pwd | rev | cut -d '/' -f 2 | rev) logs -f'
alias dcs='docker-compose -p $(pwd | rev | cut -d '/' -f 2 | rev) up -d && docker-compose -p $(pwd | rev | cut -d '/' -f 2 | rev) logs -f'
alias dcdu='docker-compose -p $(pwd | rev | cut -d '/' -f 2 | rev) down && docker-compose -p $(pwd | rev | cut -d '/' -f 2 | rev) up -d'
alias dcrs='docker-compose -p $(pwd | rev | cut -d '/' -f 2 | rev) down && docker-compose -p $(pwd | rev | cut -d '/' -f 2 | rev) up -d && docker-compose logs -p $(pwd | rev | cut -d '/' -f 2 | rev) -f'

alias vdf='vim Dockerfile'
alias vdc='vim docker-compose.yml'

function gs() { git show $1 | vim - }
alias grs='git reset --soft'
alias grh='git reset --hard'

REMOTE="lbic"
#REMOTE="y2p"
#REMOTE="vb"

alias {rzz,rz}='source $XDG_CONFIG_HOME/zsh/.zshrc'
alias {rii,ri}='$XDG_CONFIG_HOME/i3/i3bang.rb && i3-msg restart'
alias {rii,ri}='$XDG_CONFIG_HOME/sway/i3bang.rb && swaymsg reload'
alias {rww,rw}='rm -rf $XDG_CACHE_HOME/wasistlos'
alias {rxx,rx}='xmodmap $HOME/.Xmodmap'
alias rze='source $XDG_CONFIG_HOME/zsh/.zshenv'

alias bb='vim $XDG_CONFIG_HOME/i3/i3blocks.conf'
alias ee='vim $XDG_CONFIG_HOME/emacs-efs/config.el'
alias kk='vim $XDG_CONFIG_HOME/kitty/kitty.conf'
alias eed='vim $XDG_CONFIG_HOME/emacs-doom/config.el'
alias pp='vim $XDG_CONFIG_HOME/polybar/config.ini'
alias vv='vim $XDG_CONFIG_HOME/nvim/init.lua'
alias xm='vim $HOME/.Xmodmap'
alias xx='vim $XDG_CONFIG_HOME/xremap/config.yml'
alias zz='vim $XDG_CONFIG_HOME/zsh/.zshrc'
alias ze='vim $XDG_CONFIG_HOME/zsh/.zshenv'
function ii () {
    case "${XDG_SESSION_TYPE}" in
        "x11") vim $XDG_CONFIG_HOME/i3/_config ;;
        "wayland") vim $XDG_CONFIG_HOME/sway/_config ;;
        "tty")
            if [ -f "/usr/share/xsessions/i3.desktop" ]; then
                vim $XDG_CONFIG_HOME/i3/_config
            elif [ -f "/usr/share/wayland-sessions/sway.desktop" ]; then
                vim $XDG_CONFIG_HOME/sway/_config
            fi ;;
        *) exit 0 ;;
    esac
}

alias lbb='ssh $REMOTE cat $XDG_CONFIG_HOME/i3/i3blocks.conf | vim -'
alias lee='ssh $REMOTE cat $XDG_CONFIG_HOME/doom/config.el | vim -'
alias lkk='ssh $REMOTE cat $XDG_CONFIG_HOME/kitty/kitty.conf | vim -'
alias lpp='ssh $REMOTE cat $XDG_CONFIG_HOME/polybar/config.ini | vim -'
alias lvv='ssh $REMOTE cat $XDG_CONFIG_HOME/nvim/init.lua | vim -'
alias lxm='ssh $REMOTE cat $HOME/.Xmodmap | vim -'
alias lxx='ssh $REMOTE cat $XDG_CONFIG_HOME/zsh/.zshrc | vim -'
alias lze='ssh $REMOTE cat $XDG_CONFIG_HOME/zsh/.zshenv | vim -'
alias lzz='ssh $REMOTE cat $XDG_CONFIG_HOME/zsh/.zshrc | vim -'
function lii () {
    case "${XDG_SESSION_TYPE}" in
        "x11") ssh $REMOTE cat $XDG_CONFIG_HOME/i3/_config | vim - ;;
        "wayland") ssh $REMOTE cat $XDG_CONFIG_HOME/sway/_config | vim - ;;
        "tty")
            if [ -f "/usr/share/xsessions/i3.desktop" ]; then
                ssh $REMOTE cat $XDG_CONFIG_HOME/i3/_config | vim -
            elif [ -f "/usr/share/wayland-sessions/sway.desktop" ]; then
                ssh $REMOTE cat $XDG_CONFIG_HOME/sway/_config | vim -
            fi ;;
        *) exit 0 ;;
    esac
}

alias dbb='ssh $REMOTE cat $XDG_CONFIG_HOME/i3/i3blocks.conf | diff - $XDG_CONFIG_HOME/i3/i3blocks.conf'
alias dee='ssh $REMOTE cat $XDG_CONFIG_HOME/doom/config.el | diff - $XDG_CONFIG_HOME/doom/config.el'
alias dkk='ssh $REMOTE cat $XDG_CONFIG_HOME/kitty/kitty.conf | diff - $XDG_CONFIG_HOME/kitty/kitty.conf'
alias dpp='ssh $REMOTE cat $XDG_CONFIG_HOME/polybar/config.ini | diff - $XDG_CONFIG_HOME/polybar/config.ini'
alias dvv='ssh $REMOTE cat $XDG_CONFIG_HOME/nvim/init.lua | diff - $XDG_CONFIG_HOME/nvim/init.lua'
alias dxm='ssh $REMOTE cat $HOME/.Xmodmap | diff - $HOME/.Xmodmap'
alias dxx='ssh $REMOTE cat $XDG_CONFIG_HOME/xremap/config.yml | diff - $XDG_CONFIG_HOME/xremap/config.yml'
alias dze='ssh $REMOTE cat $XDG_CONFIG_HOME/zsh/.zshenv | diff - $XDG_CONFIG_HOME/zsh/.zshenv'
alias dzz='ssh $REMOTE cat $XDG_CONFIG_HOME/zsh/.zshrc | diff - $XDG_CONFIG_HOME/zsh/.zshrc'
function dii () {
    case "${XDG_SESSION_TYPE}" in
        "x11") ssh $REMOTE cat $XDG_CONFIG_HOME/i3/_config | diff - $XDG_CONFIG_HOME/i3/_config ;;
        "wayland") ssh $REMOTE cat $XDG_CONFIG_HOME/sway/_config | diff - $XDG_CONFIG_HOME/sway/_config ;;
        "tty")
            if [ -f "/usr/share/xsessions/i3.desktop" ]; then
                ssh $REMOTE cat $XDG_CONFIG_HOME/i3/_config | diff - $XDG_CONFIG_HOME/i3/_config
            elif [ -f "/usr/share/wayland-sessions/sway.desktop" ]; then
                ssh $REMOTE cat $XDG_CONFIG_HOME/sway/_config | diff - $XDG_CONFIG_HOME/sway/_config
            fi ;;
        *) exit 0 ;;
    esac
}

alias gbb='vim $HOME/git/dotfiles/i3/i3blocks.conf'
alias gee='vim $HOME/git/dotfiles/doom/config.el'
alias gkk='vim $HOME/git/dotfiles/kitty/kitty.conf'
alias gpp='vim $HOME/git/dotfiles/polybar/config.ini'
alias gvv='vim $HOME/git/dotfiles/nvim/init.lua'
alias gxm='vim $HOME/git/dotfiles/X.Org/Xmodmap'
alias gxx='vim $HOME/git/dotfiles/xremap/config.yml'
alias gze='vim $HOME/git/dotfiles/zsh/zshenv'
alias gzz='vim $HOME/git/dotfiles/zsh/zshrc'
function gii () {
    case "${XDG_SESSION_TYPE}" in
        "x11") vim $HOME/git/dotfiles/i3/_config ;;
        "wayland") vim $HOME/git/dotfiles/i3/_config ;;
        "tty")
            if [ -f "/usr/share/xsessions/i3.desktop" ]; then
                vim $HOME/git/dotfiles/i3/_config
            elif [ -f "/usr/share/wayland-sessions/sway.desktop" ]; then
                vim $HOME/git/dotfiles/sway/_config
            fi ;;
        *) exit 0 ;;
    esac
}

alias gdbb='diff $HOME/git/dotfiles/i3/i3blocks.conf $XDG_CONFIG_HOME/i3/i3blocks.conf'
alias gdee='diff $HOME/git/dotfiles/doom/config.el $XDG_CONFIG_HOME/doom/config.el'
alias gdkk='diff $HOME/git/dotfiles/kitty/kitty.conf $XDG_CONFIG_HOME/kitty/kitty.conf'
alias gdpp='diff $HOME/git/dotfiles/polybar/config.ini $XDG_CONFIG_HOME/polybar/config.ini'
alias gdvv='diff $HOME/git/dotfiles/nvim/init.lua $XDG_CONFIG_HOME/nvim/init.lua'
alias gdxm='diff $HOME/git/dotfiles/X.Org/Xmodmap $HOME/.Xmodmap'
alias gdxx='diff $HOME/git/dotfiles/xremap/config.yml $XDG_CONFIG_HOME/xremap/config.yml'
alias gdze='diff $HOME/git/dotfiles/zsh/zshenv $XDG_CONFIG_HOME/zsh/.zshenv'
alias gdzz='diff $HOME/git/dotfiles/zsh/zshrc $XDG_CONFIG_HOME/zsh/.zshrc'
function gdii () {
    case "${XDG_SESSION_TYPE}" in
        "x11") diff $HOME/git/dotfiles/i3/_config $XDG_CONFIG_HOME/i3/_config ;;
        "wayland") diff $HOME/git/dotfiles/i3/_config $XDG_CONFIG_HOME/sway/_config ;;
        "tty")
            if [ -f "/usr/share/xsessions/i3.desktop" ]; then
                diff $HOME/git/dotfiles/i3/_config $XDG_CONFIG_HOME/i3/_config
            elif [ -f "/usr/share/wayland-sessions/sway.desktop" ]; then
                diff $HOME/git/dotfiles/sway/_config $XDG_CONFIG_HOME/sway/_config
            fi ;;
        *) exit 0 ;;
    esac
}

alias ls='eza -algh --color=always --group-directories-first'   # default
alias la='eza -a    --color=always --group-directories-first'   # all files & dirs
alias ll='eza -l    --color=always --group-directories-first'   # long
alias lt='eza -aT   --color=always --group-directories-first'   # tree
alias l.='eza -a | egrep "^\."'                                 # hidden
alias lsd='eza --list-dirs */'                                  # dirs only
alias lsl='eza'                                                 # minimal
alias lso='eza --oneline'                                       # oneline

alias cat=bat
alias {catp,pcat}='bat -p'

alias -g c='| xclip -selection clipboard'           # copy stdout
alias {pwdc,pc}='pwd | xclip -selection clipboard'  # copy pwd
alias cv='cd $(xclip -out -selection clipboard)'    # move to dir in clipboard

alias -g c='| wl-copy'           # copy stdout
alias {pc,pwdc}='pwd | wl-copy'  # copy pwd
alias cv='cd $(wl-paste)'        # move to dir in clipboard

alias vpn-lbic='$XDG_CONFIG_HOME/vpn/lbic/vpn-lbic.sh'

alias vpn-unicamp='$XDG_CONFIG_HOME/vpn/unicamp/vpn-unicamp.sh'

alias vpn-samsung='$XDG_CONFIG_HOME/vpn/samsung/vpn-samsung.sh'

alias recod='$XDG_CONFIG_HOME/vpn/recod/port-binding.sh'

alias lbic='$XDG_CONFIG_HOME/vpn/lbic/port-binding.sh'

alias asp='$XDG_CONFIG_HOME/scripts/adb-mdns-pair.sh'    # ADB script for pairing
alias asc='$XDG_CONFIG_HOME/scripts/adb-mdns-scrcpy.sh'  # ADB script for connecting (scrcpy)
alias ap='adb pair'        # ADB pair
alias ac='adb connect'     # ADB connect
alias ad='adb disconnect'  # ADB disconnect
alias al='adb devices -l'  # ADB list devices
alias as='adb shell'       # ADB shell

function s() {
    adb connect 192.168.0.101:5555
    s20_ip=$(adb devices -l | grep SM_G980F | awk "{print \$1}")
    scrcpy -s $s20_ip --prefer-text
}

function sw() {
    adb connect 192.168.0.104:5555
    gw4_ip=$(adb devices -l | grep SM_R880 | awk "{print \$1}")
    scrcpy -s $gw4_ip --prefer-text
}

alias -g s20_ip='adb devices -l | grep SM_G980F | awk "{print \$1}"'
alias -g gw4_ip='adb devices -l | grep SM_R880  | awk "{print \$1}"'

alias -g s20="-s $(s20_ip)"
alias -g gw4="-s $(gw4_ip)"

alias s="scrcpy s20 --prefer-text"
alias sw="scrcpy gw4 --prefer-text"

function usd() { forx -q "${1:-1}" USD BRL }    # US Dollar
function eur() { forx -q "${1:-1}" EUR BRL }    # Euro
function gbp() { forx -q "${1:-1}" GBP BRL }    # Pound
function jpy() { forx -q "${1:-1}" JPY BRL }    # Yen
function cad() { forx -q "${1:-1}" CAD BRL }    # Canadian Dollar
function aud() { forx -q "${1:-1}" AUD BRL }    # Australian Dollar

function btc() { forx -q "${1:-1}" BTC BRL }    # Bitcoin
function eth() { forx -q "${1:-1}" ETH BRL }    # Ethereum
#function bnb() { forx -q "${1:-1}" BNB BRL }    # Binance
#function xch() { forx -q "${1:-1}" XCH BRL }    # Chia

export PATH="$HOME/.emacs.d/bin:$PATH"

#export GDK_SCALE=2
#export GDK_DPI_SCALE=0.5

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export SHELL=/usr/bin/zsh

export TERMINAL=kitty

#export THEME_CURRENT=$(cat $XDG_CONFIG_HOME/gtk-4.0/settings.ini | grep -oP '(?<=gtk-theme-name=).*')
export THEME_DARK='Adwaita-dark'
export THEME_LIGHT='Adwaita'

export GROFF_NO_SGR=1

bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down
bindkey "^E" history-substring-search-down
bindkey "^I" history-substring-search-up

# fix: workaround for history-substring-search to work with zsh-vi-mode
zvm_after_init_commands+=(
    "bindkey '^[[A' up-line-or-search" 
    "bindkey '^[[B' down-line-or-search"
)

bindkey '^H' backward-kill-word                  # ctrl+backspace: delete previous word
bindkey '5~' kill-word                           # ctrl+delete: delete next word
#bindkey '^[[3;5~' kill-word                      # ctrl+shift+delete: delete next word

# fix: workaround for kill-word to work with zsh-vi-mode
zvm_after_init_commands+=(
    "bindkey '^H' backward-kill-word"
    "bindkey '5~' kill-word"
)

zvm_vi_yank () {
    zvm_yank
    printf %s "${CUTBUFFER}" |  wl-copy -n
    zvm_exit_visual_mode
}

#zvm_vi_yank () {
#    zvm_yank
#    printf %s "${CUTBUFFER}" | xclip -selection clipboard
#    zvm_exit_visual_mode
#}

#bindkey -a 'n' vi-backward-char
#bindkey -a 'e' down-line-or-history
#bindkey -a 'i' up-line-or-history
#bindkey -a 'o' vi-forward-char

#bindkey -a 'k' vi-repeat-search
#bindkey -a 'K' vi-rev-repeat-search
#bindkey -a 's' vi-insert
#bindkey -a 'S' vi-insert-bol
#bindkey -a 'l' vi-forward-word-end
#bindkey -a 'L' vi-forward-blank-word-end

#eval $(keychain --noask --eval --quiet id_ed25519)

eval "$(zoxide init --cmd cd zsh)"
