keymap:

  - name: copy/paste/cut - terminal
    application:
      only: [kitty, dropdown_terminal, dropdown_python]
    remap:
      F16: C-S-x
      F17: C-S-c
      F18: C-S-v

  - name: paste - Emacs (insert)
    application:
      #only: Emacs
      only: emacs
    remap:
      F16: M-x
      F18: [C-r, SHIFT-apostrophe, space]

  - name: cut
    exact_match: true
    application:
      #not: Emacs
      not: emacs
    remap:
      F16: CTRL-x

  - name: copy/paste/cut - general
    application:
    remap:
      F16: C-x
      F17: C-c
      F18: C-v
