keymap:

  - name: copy and paste in Terminal
    application:
      only: kitty
    remap:
      F17: C-S-c
      F18: C-S-v

    remap:
    remap:

keymap:
  - name: copy and paste - general
    application:
      not: [kitty, emacs, dropdown_terminal, dropdown_python]
    remap:
      F17: C-c
      F18: C-v
