keymap:

  - name: copy/paste/cut - terminal
    application:
      only: [kitty, dropdown_terminal, dropdown_python]
    remap:
      F16: C-S-x
      F17: C-S-c
      F18: C-S-v

  - name: paste - Emacs (insert)
    application:
      #only: Emacs
      only: emacs
    remap:
      F16: M-x
      F18: [C-r, SHIFT-apostrophe, space]

  - name: cut
    exact_match: true
    application:
      #not: Emacs
      not: emacs
    remap:
      F16: CTRL-x

  - name: copy/paste/cut - general
    application:
    remap:
      F16: C-x
      F17: C-c
      F18: C-v

# Emacs
  - name: Window navigation
    exact_match: true
    application:
      #only: Emacs
      only: emacs
    remap:
      Super_L-left: [C-w, C-h]
      Super_L-down: [C-w, C-j]
      Super_L-up: [C-w, C-k]
      Super_L-right: [C-w, C-l]

  - name: Previous window
    exact_match: true
    application:
      #only: Emacs
      only: emacs
    remap:
      F19: [C-w, C-w]

  - name: Kill buffer and window
    exact_match: true
    application:
      #only: Emacs
      only: emacs
    remap:
      SUPER-ALT-w: [space, b, k]
      SUPER-ALT-q: [C-w, q]

# dead_acute
  - name: forward char / dead_acute
    exact_match: true
    application:
      #not: Emacs
      not: emacs
    remap:
      F13:
        remap:
          # apostrophe
          F13: [APOSTROPHE, SPACE]
          space: [APOSTROPHE, SPACE]
          # cedilla
          c: [APOSTROPHE, c]
          SHIFT-c: [APOSTROPHE, SHIFT-c]
          # lowercase vowels
          a: [APOSTROPHE, a]
          e: [APOSTROPHE, e]
          i: [APOSTROPHE, i]
          o: [APOSTROPHE, o]
          u: [APOSTROPHE, u]
          # uppercase vowels
          SHIFT-a: [APOSTROPHE, SHIFT-a]
          SHIFT-e: [APOSTROPHE, SHIFT-e]
          SHIFT-i: [APOSTROPHE, SHIFT-i]
          SHIFT-o: [APOSTROPHE, SHIFT-o]
          SHIFT-u: [APOSTROPHE, SHIFT-u]
          # miscellaneous lowercase
          n: [APOSTROPHE, SPACE, n]
          m: [APOSTROPHE, SPACE, m]
          r: [APOSTROPHE, SPACE, r]
          s: [APOSTROPHE, SPACE, s]
          t: [APOSTROPHE, SPACE, t]
          # miscellaneous uppercase
          SHIFT-n: [APOSTROPHE, SPACE, SHIFT-n]
          SHIFT-m: [APOSTROPHE, SPACE, SHIFT-m]
          SHIFT-r: [APOSTROPHE, SPACE, SHIFT-r]
          SHIFT-s: [APOSTROPHE, SPACE, SHIFT-s]
          SHIFT-t: [APOSTROPHE, SPACE, SHIFT-t]
      SHIFT-F13:
        remap:
          # double quotes
          SHIFT-F13: [SHIFT-APOSTROPHE, SPACE]
          F13: [SHIFT-APOSTROPHE, SPACE]
          space: [SHIFT-APOSTROPHE, SPACE]
          # tilde lowercase
          a: [SHIFT-GRAVE, a]
          o: [SHIFT-GRAVE, o]
          n: [SHIFT-GRAVE, n]
          # tilde uppercase
          SHIFT-A: [SHIFT-GRAVE, SHIFT-A]
          SHIFT-O: [SHIFT-GRAVE, SHIFT-O]
          SHIFT-N: [SHIFT-GRAVE, SHIFT-N]
          # tilde miscellaneous
          DOT: [SHIFT-GRAVE, SPACE, SLASH, DOT]
          SLASH: [SHIFT-GRAVE, SPACE, SLASH]
