keymap:
  - name: ctrl+j to enter
    remap:
      C-j: enter

  - name: navigate2ws
    remap:
      C-SUPER-j:
        launch: ["bash", "-c", "~/.config/scripts/navigate2ws_next.py --next"]
      C-SUPER-k: 
        launch: ["bash", "-c", "~/.config/scripts/navigate2ws_next.py --prev"]
  - name: vim motion
    remap:
      rightalt-h:
        launch: ["bash", "-c", "ydotool key 105:1 105:0"]
