keymap:

    remap:
  - name: copy and paste in Terminal
    application:
      only: kitty
    remap:
      rightalt-c:
        launch: ["bash", "-c", "ydotool key --clearmodifiers 'ctrl+shift+c'"]
      rightalt-v:
        launch: ["bash", "-c", "ydotool key --clearmodifiers 'ctrl+shift+v'"]

    remap:
    remap:

keymap:
  - name: copy and paste - general
    application:
      not: [kitty, emacs, dropdown_terminal, dropdown_python]
    remap:
      F17: C-c
      F18: C-v
