virtual_modifiers:
  - Henkan
  - Muhenkan

shared:
  terminals: &terminals
    - kitty
    - dropdown_terminal
    - dropdown_python
  scratchpads: &scratchpads
    - dropdown_terminal
    - dropdown_python
    - scrcpy
    - Brave-browser-beta
    - Keymapp
    - keymapp
  emacs-ssh: &emacs-ssh
    - "/.*: emacsclient --create-frame --alternate-editor=.*emacs.*/"
    - "/.*: emacsclient -c -a .*emacs.*/"
    - "/.*: eg/"

keymap:

  - name: copy/paste/cut - terminal
    application:
      only: *terminals
    remap:
      F16: Ctrl-Shift-x
      F17: Ctrl-Shift-c
      F18: Ctrl-Shift-v



  - name: copy/paste/cut - general
    application:
      not: [Emacs, emacs]
    remap:
      F16: Ctrl-x
      F17: Ctrl-c
      F18: Ctrl-v

  - name: Window navigation
    exact_match: true
    application:
      not: [Emacs, emacs]
    remap:
      Super_L-left:  { launch: ["bash", "-c", "$XDG_CONFIG_HOME/scripts/mouse-warp.sh left"] }
      Super_L-down:  { launch: ["bash", "-c", "$XDG_CONFIG_HOME/scripts/mouse-warp.sh down"] }
      Super_L-up:    { launch: ["bash", "-c", "$XDG_CONFIG_HOME/scripts/mouse-warp.sh up"] }
      Super_L-right: { launch: ["bash", "-c", "$XDG_CONFIG_HOME/scripts/mouse-warp.sh right"] }

  - name: Kill buffer and window
    exact_match: true
    application:
      only: [Emacs, emacs]
    remap:
      Super-w: [space, b, k]
      Super-Alt-q: [C-w, q]

  - name: Window navigation
    exact_match: true
    application:
      only: kitty
    window:
      only: *emacs-ssh
    remap:
      Super_L-left:  [C-w, C-h]
      Super_L-down:  [C-w, C-j]
      Super_L-up:    [C-w, C-k]
      Super_L-right: [C-w, C-l]

  - name: delete next word
    application:
      only: kitty
    remap:
      Ctrl-Shift-Backspace: Ctrl-Delete

  - name: Prev/Next tab
    exact_match: true
    application:
      only: brave-browser
    window:
      only: ["better onetab - Brave", "Extensions - Brave", "chrome://newtab - Brave", "Chrome Web Store - Brave"]
    remap:
      Shift-N: Alt-Left        # go back
      Shift-E: Ctrl-Tab        # next tab
      Shift-I: Ctrl-Shift-Tab  # previous tab
      Shift-O: Alt-Right       # go forward
      Shift-X: Ctrl-Shift-T    # reopen tab

  - name: forward char / dead_acute
    exact_match: true
    application:
      not: [Emacs, emacs]
    remap:
      F13:
        remap:
          # apostrophe
          F13: [APOSTROPHE, SPACE]
          space: [APOSTROPHE, SPACE]
          # cedilla
          c: [APOSTROPHE, c]
          Shift-c: [APOSTROPHE, Shift-c]
          # lowercase vowels
          a: [APOSTROPHE, a]
          e: [APOSTROPHE, e]
          i: [APOSTROPHE, i]
          o: [APOSTROPHE, o]
          u: [APOSTROPHE, u]
          # uppercase vowels
          Shift-a: [APOSTROPHE, Shift-a]
          Shift-e: [APOSTROPHE, Shift-e]
          Shift-i: [APOSTROPHE, Shift-i]
          Shift-o: [APOSTROPHE, Shift-o]
          Shift-u: [APOSTROPHE, Shift-u]
          # miscellaneous lowercase
          n: [APOSTROPHE, SPACE, n]
          m: [APOSTROPHE, SPACE, m]
          r: [APOSTROPHE, SPACE, r]
          s: [APOSTROPHE, SPACE, s]
          t: [APOSTROPHE, SPACE, t]
          # miscellaneous uppercase
          Shift-n: [APOSTROPHE, SPACE, Shift-n]
          Shift-m: [APOSTROPHE, SPACE, Shift-m]
          Shift-r: [APOSTROPHE, SPACE, Shift-r]
          Shift-s: [APOSTROPHE, SPACE, Shift-s]
          Shift-t: [APOSTROPHE, SPACE, Shift-t]
      Shift-F13:
        remap:
          # double quotes
          F13: [Shift-APOSTROPHE, SPACE]
          space: [Shift-APOSTROPHE, SPACE]
          #Shift-F13: [Shift-APOSTROPHE, SPACE]
          # tilde lowercase
          a: [Shift-GRAVE, a]
          o: [Shift-GRAVE, o]
          n: [Shift-GRAVE, n]
          # tilde uppercase
          Shift-A: [Shift-GRAVE, Shift-A]
          Shift-O: [Shift-GRAVE, Shift-O]
          Shift-N: [Shift-GRAVE, Shift-N]
          # tilde miscellaneous
          Shift-F13: [Shift-GRAVE, SPACE]
          SLASH:     [Shift-GRAVE, SPACE, SLASH]
          DOT:       [Shift-GRAVE, SPACE, SLASH, DOT]
          # tilde paths
          g: [Shift-GRAVE, SPACE, SLASH, g,i,t, SLASH]
          d: [Shift-GRAVE, SPACE, SLASH, g,i,t, SLASH, d,o,t,f,i,l,e,s, SLASH]
          c: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH]
          s: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, s,c,r,i,p,t,s, SLASH]
          v: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, n,v,i,m, SLASH]
          x: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, x,r,e,m,a,p, SLASH]
          w: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, w,a,y,b,a,r, SLASH]
          z: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, z,s,h, SLASH]
          i: [Shift-GRAVE, SPACE, SLASH, DOT, c,o,n,f,i,g, SLASH, i,3, SLASH]


  - name: navigate through emoji categories
    application:
      only: [emote, Emote]
    remap:
      Shift-N: Ctrl-Shift-Tab  # previous category
      Shift-O: Ctrl-Tab        # next category
      Shift-I: Ctrl-F          # focus search
      Ctrl-n:  left            # arrow left
      Ctrl-e:  down            # arrow down
      Ctrl-i:  up              # arrow up
      Ctrl-o:  right           # arrow right

  - name: window navigation from scratchpads
    application:
      only: *scratchpads
    remap:
      Super-Left:  { launch: ["i3-msg", "focus", "output", "left"] }
      Super-Right: { launch: ["i3-msg", "focus", "output", "right"] }

  - name: miscellaneous text - macros (terminal)
    application:
      only: *terminals
    remap:
      # macro
      Alt_R-s: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/address_1)\" | xclip -sel clip && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-t: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/address_2)\" | xclip -sel clip && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-g: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/address_3)\" | xclip -sel clip && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-c: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/zip_code)\"  | xclip -sel clip && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-d: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/phone)\"     | xclip -sel clip && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-n: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/email_1)\"   | xclip -sel clip && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-l: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/email_2)\"   | xclip -sel clip && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-u: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/email_3)\"   | xclip -sel clip && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-h: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/name)\"      | xclip -sel clip && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-i: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"$(<$XDG_CONFIG_HOME/macros/id)\"        | xclip -sel clip && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }

  - name: miscellaneous text - macros
    application:
      not: *terminals
    remap:
      # macro
      Alt_R-s: { launch: ["bash", "-c", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/address_1 | xclip -sel clip && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-t: { launch: ["bash", "-c", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/address_2 | xclip -sel clip && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-g: { launch: ["bash", "-c", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/address_3 | xclip -sel clip && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-c: { launch: ["bash", "-c", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/zip_code  | xclip -sel clip && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-d: { launch: ["bash", "-c", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/phone     | xclip -sel clip && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-n: { launch: ["bash", "-c", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/email_1   | xclip -sel clip && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-l: { launch: ["bash", "-c", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/email_2   | xclip -sel clip && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-u: { launch: ["bash", "-c", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/email_3   | xclip -sel clip && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-h: { launch: ["bash", "-c", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/name      | xclip -sel clip && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-i: { launch: ["bash", "-c", "sleep 0.1 && cat $XDG_CONFIG_HOME/macros/id        | xclip -sel clip && ydotool key 29:1 47:1 47:0 29:0"] }

  - name: miscellaneous text - currency & superscript (terminal)
    application:
      only: *terminals
    remap:
      # currency
      Alt_R-e: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"€\"  | xclip -sel clip && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-p: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"£\"  | xclip -sel clip && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-y: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"￥\" | xclip -sel clip && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-r: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"₽\"  | xclip -sel clip && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      # superscript
      Alt_R-a: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"ª\"  | xclip -sel clip && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }
      Alt_R-o: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"º\"  | xclip -sel clip && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0"] }

  - name: miscellaneous text - currency & superscript
    application:
      not: *terminals
    remap:
      # currency
      Alt_R-e: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"€\"  | xclip -sel clip && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-p: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"£\"  | xclip -sel clip && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-y: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"￥\" | xclip -sel clip && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-r: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"₽\"  | xclip -sel clip && ydotool key 29:1 47:1 47:0 29:0"] }
      # superscript
      Alt_R-a: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"ª\"  | xclip -sel clip && ydotool key 29:1 47:1 47:0 29:0"] }
      Alt_R-o: { launch: ["bash", "-c", "sleep 0.1 && echo -n \"º\"  | xclip -sel clip && ydotool key 29:1 47:1 47:0 29:0"] }


#  - name: presentation with pdfpc
#    exact_match: true
#    application:
#      only: pdfpc
#    remap:
#      KEY_R: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--scene", "camera"] }
#      KEY_S: KEY_1
#      KEY_T: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--scene", "presentation"] }
#      KEY_W: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--scene", "scene-4"] }
#      KEY_F: KEY_2
#      KEY_P: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--scene", "scene-6"] }
#      KEY_X: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--scene", "scene-7"] }
#      KEY_C: KEY_3
#      KEY_D: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--scene", "scene-9"] }
#      KEY_B: { launch: ["$XDG_CONFIG_HOME/scripts/obs-tools.py", "--record"] }
#      KEY_G: KEY_MINUS
#      KEY_V: S-EQUAL
#      KEY_Q: KEY_5
#      KEY_A: KEY_4
#      #KEY_Z:
#      KEY_SPACE: KEY_DOWN
#      KEY_ESC: KEY_UP
#      #KEY_TAB:
