keymap:

  - name: copy/paste/cut - terminal
    application:
      only: [kitty, dropdown_terminal, dropdown_python]
    remap:
      F16: C-S-x
      F17: C-S-c
      F18: C-S-v

    remap:
    remap:

  - name: copy/paste/cut - general
    application:
    remap:
      F16: C-x
      F17: C-c
      F18: C-v
