keymap:

  - name: copy/paste/cut - terminal
    application:
      only: [kitty, dropdown_terminal, dropdown_python]
    remap:
      F16: C-S-x
      F17: C-S-c
      F18: C-S-v

  - name: paste - Emacs (insert)
    application:
      #only: Emacs
      only: emacs
    remap:
      F16: M-x
      F18: [C-r, SHIFT-apostrophe, space]

  - name: cut
    exact_match: true
    application:
      #not: Emacs
      not: emacs
    remap:
      F16: CTRL-x

  - name: copy/paste/cut - general
    application:
    remap:
      F16: C-x
      F17: C-c
      F18: C-v

# Emacs
  - name: Window navigation
    exact_match: true
    application:
      #only: Emacs
      only: emacs
    remap:
      Super_L-left: [C-w, C-h]
      Super_L-down: [C-w, C-j]
      Super_L-up: [C-w, C-k]
      Super_L-right: [C-w, C-l]

  - name: Previous window
    exact_match: true
    application:
      #only: Emacs
      only: emacs
    remap:
      F19: [C-w, C-w]
